### PR TITLE
Add "ACL2s Systems Programming" ACL2 Workshop materials

### PR DESCRIPTION
**Pull request by mister-walter**
Add the supporting materials for our ACL2s Systems Programming ACL2
workshop paper.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
Andrew, thanks for the contribution, but would you please change the target from acl2:master to acl2:testing?  That's the usual target for pull requests.  Thanks in advance.

**Comment by mister-walter** [comment]
Done, sorry about that!

**Comment by MattKaufmann** [comment]
Testing failed for books/workshops/2022/walter-manolios/examples/p-formula-equiv.lisp\
 with the following error -- maybe a .acl2 file is missing.

    ACL2 Error in (CERTIFY-BOOK "p-formula-equiv" ...):  The ttag :EV-FNCALL-W-OK
    associated with file <http://leeroy2.defthm.com/job/acl2-testing/ws/books/acl2s/defdata/builtin-combinators.lisp is not among the set of ttags permitted
    in the current context, specified as follows:
      NIL.
    See :DOC defttag.

**Comment by mister-walter** [comment]
Ah - those files are not intended to be certified. I will rename them to `.lsp` files and make another PR.

**Pull request merged**
