### PR TITLE
Fix Ankit's book

### PR DESCRIPTION
**Pull request by maxvonhippel**
I *believe* this PR will make [Ankit's book](https://github.com/acl2/acl2/pull/1549) pass the testing CI.  I am not 100% certain, but I'm more than 50% certain, if that's worth anything.

Basically, all I did was copy the `cert.acl2` which worked for my book, remove the `make.sh` and `cert_pl_exclude`, and then run the following and confirm that it worked:

```
ACL2=$(which acl2) cert.pl -j32 top.lisp
```

### CODE REVIEW

**Comment by ericwhitmansmith** [comment]
Thanks, Max!  Can you change this PR to merge into testing instead of master?

**Comment by maxvonhippel** [comment]
Done.

**Comment by ericwhitmansmith** [comment]
Looks like there is still an issue:

http://leeroy.defthm.com/job/acl2-testing/4250/console

Can you try deleting the cert.image file?  I think that may be what is trying to call acl2s.

**Comment by maxvonhippel** [comment]
Yes, done

**Comment by maxvonhippel** [comment]
(Going to sleep now, but if this is still broken in the morning I can try to troubleshoot some more tomorrow)

**Comment by maxvonhippel** [comment]
Here you go: https://github.com/acl2/acl2/pull/1552

**Pull request merged**
