### PR TITLE
Refactoring: Use a fast-alist-based topological sort (reusing a centaur/misc book).

### PR DESCRIPTION
**Pull request by harshrc**
I apologize for all the unnecessary merge commits. I will try to avoid it in the future.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
Hi acl2-books,

I tend to accept pull requests blindly when they are quite clearly
restricted to the author's own work.  This is such a pull request, for
example.  Is there any reason why I should be more hesitant?

That said, here is a question for Harsh in particular, on this pull
request:

In books/acl2s/cgen/topological-sort.lisp I see this comment:

;;; Modified from centaur/misc/ and centaur/depgraph books.

Might you be more specific about which particular books?  (Note that
centaur/depgraph is a directory.  Perhaps you are referring to
centaur/depgraph/toposort.lisp there?  Have you considered adding a
comment saying a bit more than "Modified", e.g., maybe your top-level
function replaces some other top-level function because ....)

Thanks --
-- Matt

**Comment by airbornemihir** [comment]
@harshrc Since you seemed concerned about unnecessary merge commits, I thought I'd offer the same kind of help Keshav did in #805. You can run the following to clean up this pull request by removing all the unnecessary merge commits, while retaining proper attribution for your commits.
I haven't tested these changes myself, but I verified (using git diff) that the contents are exactly the same as after your original commits.

git status # check that everything looks normal, i.e. no uncommitted changes
git checkout master # if you're not already on master
git fetch https://github.com/airbornemihir/acl2.git pull-request-854
git reset --hard FETCH_HEAD
git push -f

**Comment by harshrc** [comment]
Hi Matt,
I dont quite understand your first question.

With regard to your second paragraph, I don't remember the details.
Topological sort is a standard algorithm, I did not want to waste time in
re-inventing, so I studied the implementation by Sol and Jared in the
centaur books and adapted the relevant code that worked in the context of
Cgen. Is there some licensing/copyright issue here? I am closing my
pull-request.

**Comment by harshrc** [comment]
I will try get this back into my mental stack and clarify the comments/code
and submit another pull request later.
Thanks, Matt.

**Pull request closed without merging**
