### PR TITLE
ACL2 Sedan changes sync.

### PR DESCRIPTION
**Pull request by harshrc**

### CODE REVIEW

**Comment by ragerdl** [comment]
I still see these.  Jenkins at home seems to be down today for some reason.  @harshrc If there's some hurry on this, and you can confirm that you've built all the books to completion with these CL's, then I'll go ahead and merge it.  Else, I'll wait until I figure out what's up with Jenkins once I get home.

**Comment by harshrc** [comment]
Theres no hurry.

**Comment by ragerdl** [comment]
Hi @harshrc ,

Did the books certify?  I'm getting an error:

http://leeroy.defthm.com/job/acl2-testing/146/console

It's possible that I need to clean the leeroy workspace, but off the cuff, it looks like an ACL2(s) source code problem.

David

**Comment by harshrc** [comment]
Ahh. I seemed to have certified all the cgen/defdata books (through a script) and also did make basic before the pull request. 
but this top-level ACL2 Sedan specific book got left out. 
Sorry, I should have done make acl2s too.
I have commited the fix. Do you know how to push and then modify this pull-request? Keshav once told me this is possible.

**Comment by harshrc** [comment]
@ragerdl 
ok, i have pushed the commit that fixes this. make acl2s now succeeds. 
my apologies again.

**Comment by ragerdl** [comment]
Hi @harshrc ,

The pull-request is based off the status of the branch from which you made the pull-request.  In this case you made the pull-request based on the master branch, and you also updated the master branch later, so the pull-request was updated automatically.

Thanks for the contribution~
David

**Pull request merged**
