### PR TITLE
`chmod a-x`, whitespace & indentation cleanup

### PR DESCRIPTION
**Pull request by kini**
I noticed there were some files in the repository that were marked as
executable despite not actually being executable programs or scripts.
This commit marks those as non-executable as they should be.

While doing this, I figured that if I was touching these files anyway,
I might as well do some whitespace and indentation cleanup on them as
well.  In some cases I expanded that whitespace and indentation
cleanup to other files in the same directory too.

----

@MattKaufmann, can you `chmod a-x graphics/{l,}logo.gif` and commit that as well? I'd have done that in this commit too, but those two files aren't inside the books directory and so I would have triggered your purity script.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
I made those two .gif files not-executable.

I'm not sure what to do with this pull request.  There is a massive amount to go through if I use the web interface.  Probably it's fine for me simply to accept it without checking.  But then why not just leave out the middleman and give you (Keshav) push access, at least to the testing branch?  (I think maybe Alessandro has that.)

**Comment by kini** [comment]
Yeah, there are a few people who have push access, including Alessandro, Sol, David, etc. In fact, I used to have push access (admin access, actually) because I'm the one who created the acl2 organization on github, and this very repository. I "demoted" myself some time last year since I didn't really meet the requirements mentioned in `:doc github-commit-code-using-push` and `:doc github-commit-code-using-pull-requsts`. I think I do meet those requirements now, so I'll talk to David about regaining push access.

Anyway, for this PR, what you could do is assume that my description of the changes is correct, and then let me know what you think of the changes given that assumption. For example, do you agree that it's desirable to fix the executability permissions of these files? Do you object to me performing a whitespace / indentation cleanup on these files?

By the way, if you click the following link you can see a "whitespace ignored" view of the diff in the web interface, which should be much easier to read: https://github.com/acl2/acl2/pull/787/files?w=1

Also, here is the list of files I changed (including both permissions changes and whitespace/indentation cleanup changes):

```
$ git diff --ignore-all-space --stat chmod-a-x-cleanup^!
 books/bdd/benchmarks.acl2                                                                  |   0
 books/bdd/bit-vector-reader.lsp                                                            |   0
 books/data-structures/defalist.acl2                                                        |   0
 books/data-structures/define-defstructure-package.lsp                                      |   0
 books/data-structures/define-u-package.lsp                                                 |   0
 books/data-structures/deflist.acl2                                                         |   0
 books/data-structures/memories/cert.acl2                                                   |   0
 books/data-structures/structures.acl2                                                      |   0
 books/data-structures/utilities.acl2                                                       |   0
 books/finite-set-theory/set-theory.acl2                                                    |   0
 books/misc/dft-ex.acl2                                                                     |   0
 books/powerlists/defpkg.lsp                                                                |   0
 books/projects/hybrid-systems/abs.lisp                                                     |   2 +-
 books/projects/hybrid-systems/arith-nsa4.lisp                                              |   0
 books/projects/hybrid-systems/cert.acl2                                                    |   0
 books/projects/hybrid-systems/computed-hints.lisp                                          |   0
 books/projects/hybrid-systems/eexp.lisp                                                    |   0
 books/projects/hybrid-systems/example.lisp                                                 |   0
 books/projects/hybrid-systems/nsa.lisp                                                     |   0
 books/projects/hybrid-systems/o-real-p.lisp                                                |   0
 books/projects/hybrid-systems/phi-exists.lisp                                              |   0
 books/projects/hybrid-systems/phi-properties.lisp                                          |   0
 books/projects/hybrid-systems/phi-unique.lisp                                              |   0
 books/projects/hybrid-systems/tm-floor.lisp                                                |   0
 books/projects/masc/README                                                                 |   0
 books/projects/masc/examples/Makefile                                                      |   1 -
 books/projects/masc/examples/README                                                        |   0
 books/projects/masc/examples/hello.cpp                                                     |   1 -
 books/projects/masc/examples/imul/command_script.tcl                                       |   0
 books/projects/masc/examples/imul/imul.cpp                                                 |   0
 books/projects/masc/examples/imul/imul.vs                                                  |   0
 books/projects/masc/examples/imul/proof.lisp                                               |   8 ++++----
 books/projects/masc/include/masc.h                                                         |   1 -
 books/projects/masc/lisp/Makefile                                                          |   1 -
 books/projects/masc/lisp/translate.lisp                                                    |   0
 books/projects/masc/src/Makefile                                                           |   1 -
 books/projects/masc/src/main.c                                                             |   0
 books/projects/masc/src/masc-skel                                                          |   2 --
 books/projects/masc/src/output.c                                                           |   0
 books/projects/masc/src/parser.h                                                           |   0
 books/projects/masc/src/parser.l                                                           |   0
 books/projects/masc/src/parser.y                                                           |   0
 books/projects/sidekick/public/icons/kookamara.png                                         | Bin
 books/projects/wp-gen/examples/sum.lsp                                                     |   0
 books/std/osets/cert.acl2                                                                  |   1 -
 books/workshops/2004/legato/support/Readme.lsp                                             |   0
 books/workshops/2004/legato/support/generic-theories.lisp                                  |   1 -
 books/workshops/2004/legato/support/generic-theory-alternative-induction-mult.lisp         |   2 --
 books/workshops/2004/legato/support/generic-theory-alternative-induction-sum.lisp          |   1 -
 books/workshops/2004/legato/support/generic-theory-loop-invariant-mult.lisp                |   2 --
 books/workshops/2004/legato/support/generic-theory-loop-invariant-sum.lisp                 |   1 -
 books/workshops/2004/legato/support/generic-theory-tail-recursion-mult.lisp                |   1 -
 books/workshops/2004/legato/support/generic-theory-tail-recursion-sum.lisp                 |   0
 books/workshops/2004/legato/support/nqthm/generic-theories.events                          |   1 -
 books/workshops/2004/legato/support/nqthm/generic-theory-alternative-induction-mult.events |   2 --
 books/workshops/2004/legato/support/nqthm/generic-theory-alternative-induction-sum.events  |   0
 books/workshops/2004/legato/support/nqthm/generic-theory-loop-invariant-mult.events        |   0
 books/workshops/2004/legato/support/nqthm/generic-theory-loop-invariant-sum.events         |   0
 books/workshops/2004/legato/support/nqthm/generic-theory-tail-recursion-mult.events        |   0
 books/workshops/2004/legato/support/nqthm/generic-theory-tail-recursion-sum.events         |   0
 books/workshops/2004/legato/support/nqthm/modularithmetic-98.events                        |   0
 books/workshops/2004/legato/support/nqthm/proof-by-generalization-mult.events              |   0
 books/workshops/2004/legato/support/nqthm/proof-by-generalization-sum.events               |   1 -
 books/workshops/2004/legato/support/proof-by-generalization-mult.lisp                      |   1 -
 books/workshops/2004/legato/support/proof-by-generalization-sum.lisp                       |   1 -
 books/workshops/2004/manolios-srinivasan/support/Supporting-Books/certify.lsp              |   2 --
 books/workshops/2004/schmaltz-borrione/support/certify.acl2                                |   1 -
 books/workshops/2004/sumners-ray/support/invp.lsp                                          |   4 ----
 books/workshops/2007/schmaltz/genoc-v1.0/generic-modules/readme                            |   1 -
 books/workshops/2014/puri-ray-hao-xie/support/LICENSE                                      |   1 -
 books/workshops/2014/puri-ray-hao-xie/support/Make.lsp                                     |   1 -
 books/workshops/2014/puri-ray-hao-xie/support/README                                       |   0
 books/workshops/2014/puri-ray-hao-xie/support/functions.lisp                               |   0
 books/workshops/2014/puri-ray-hao-xie/support/general-theorems.lisp                        |   1 -
 books/workshops/2014/puri-ray-hao-xie/support/semantics.lisp                               |   1 -
 books/workshops/2014/puri-ray-hao-xie/support/seq-pp-equivalence.lisp                      |   2 --
 books/workshops/2014/puri-ray-hao-xie/support/superstep-construction.lisp                  |   0
 books/xdoc/fancy/index-seo.php                                                             |   0
 books/xdoc/fancy/xslt.js                                                                   |   0
 79 files changed, 5 insertions(+), 41 deletions(-)
```

**Comment by MattKaufmann** [comment]
Thanks; the whitespace-only diffs were very helpful.

I think the changes you made were worthwhile.  I don't know how to evaluate _how_ worthwhile, but since it was you or Oracle who supported the changes, they're OK with me.

In a small number of cases I see that you deleted extra blank lines.  Some folks seem to like extra blank lines (not me though, actually); I hope this doesn't annoy them.

I'll accept the pull request now.

**Comment by kini** [comment]
My procedure was essentially to convert tabs to spaces with a `tab-width` of `8` using `M-x untabify`, then `M-x whitespace-cleanup` (which collapses multiple trailing newlines in a file to a single trailing newline if `require-final-newline` is non-nil (as I have it), else deletes multiple trailing newlines altogether), then, if it was a lisp file, going through the file and running `indent-pp-sexp` (whose behavior depends on the `lisp-indent-function` set for various symbols in `emacs-acl2.el`) on each top-level s-expression. I also made a few other discretionary changes, or skipped modifying indentation on certain forms, etc.

**Comment by MattKaufmann** [comment]
Wow -- looks like a lot of work, Keshav!  I appreciate your diligence.

-- Matt

**Comment by kini** [comment]
Sure, and thank you for the review and merge. It wasn't that much work -- I set up a couple keyboard macros and it went by pretty quickly :)

**Pull request merged**
