### PR TITLE
[WIP] Smtlink migrated to projects, documentation added (need an update for the conflict after current testing branch is merged)

### PR DESCRIPTION
**Pull request by pennyan**
Smtlink is now under projects/smtlink. It also provides some documentation about how to install z3 and how to use smtlink.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
Have you built the manual in an environment where z3 is not installed?

**Comment by pennyan** [comment]
Hi @MattKaufmann , in my experience, "make manual" will produce an error when z3 is not installed. I'm wondering if z3 is already installed in the regression test environment.

**Comment by MattKaufmann** [comment]
Probably z3 is not typically installed when regressions are run -- at least, not when I run them.  That may change, but I think it's important to support building the manual in environments where z3 is not installed.  The discussion at Issue 824 is relevant here; it seems likely that soon, it will be easy to arrange that the manual builds whether or not z3 is installed.  Until then, we should not accept your pull request.

I'm still github-ignorant, so I don't know how best to prevent this pull request from being accepted until Issue 824 is resolved.

**Comment by pennyan** [comment]
Should I close this pull request and then pull it out after issue #824 is solved?

**Comment by MattKaufmann** [comment]
That seems reasonable to me, though I don't know enough about git/github to understand what will happen if books/projects/doc.lisp changes before you submit your pull request again later on.

**Comment by kini** [comment]
You could just leave it open, maybe change the title to say "[WIP]" at the beginning. Then later when you're ready to merge it, just update the branch.

**Comment by pennyan** [comment]
@kini OH, I remember you teaching me how to do that once. Good. I will do that!

**Comment by MattKaufmann** [comment]
After this latest push, have you built the manual in an environment where z3 is not installed?

**Comment by pennyan** [comment]
Yes. I removed one of the .cert file for one of the z3-dependent books, made sure the system can't find z3, and then rebuilt the manual. The build is successful and no certification is done on that book. Let me know if you think I should do a complete rebuild.

**Comment by solswords** [comment]
My last commit seems to have left this with a trivial conflict -- I'm not sure why; looks like your merge commits only have a single parent each?

**Comment by pennyan** [comment]
Hi @solswords , my file books/build/doc.lisp is from a previous commit of yours. Maybe then when you update it, mine is still the old version? What do you mean by my merge commits only have a single parent each? I think I can resolve this problem by fetching your most recent commit and then update this pull request accordingly.

**Comment by kini** [comment]
screenshot from 2018-02-26 14-44-58

Note how aa8e641e0 has the commit message "Merge remote-tracking branch 'remotes/upstream/master'" even though it's not merging together two parent commits. Meanwhile ad6919c48 has the same message but does merge together two parent commits, 154001311 and 62d937032. I think that's what Sol meant by saying that your merge commit had only a single parent.

**Comment by ragerdl** [comment]
It may be wise* for Yan to (1) close this pull request, (2) create a new branch in her repo, (3) copy her changed files into that new branch, (4) commit those files to her new branch (with the informative commit messages that she's already written), and then (5) create a new pull request based on that new branch.


*I haven't really been following this; yet, I suspect the above is a good idea in this case.

**Comment by kini** [comment]
I think everything looks fine now actually...

**Comment by ragerdl** [comment]
Hi @pennyan , can you please do a complete rebuild?  In this particular methodology, you'd really need to remove the certificates for each of the books that uses Z3.  It's probably easier (and more reliable) to clean everything, hide `z3`, and then build the manual.  Thanks for your diligence!

**Comment by pennyan** [comment]
Hi @kini and @ragerdl , thanks for the information. I've figured out that the missing parent is because I used rebase instead of merge. I will definitely stick with using merge in the future when dealing with upstreams... I will do the rebuild and let you know if it passed!

**Pull request closed without merging**
