### PR TITLE
ACL2 can certify now one of the demos without including "arithmetic"

### PR DESCRIPTION
**Pull request by nadezhin**
Remove `(include-book "arithmetic/top-with-meta" :dir :system)` from `demos/tutorial-problems/equivalence-of-two-functions/kaufmann.lisp`.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
Cool!  I wonder why I thought I needed that lemma -- maybe ACL2 has
improved since the time I developed that book....

-- Matt

**Comment by MattKaufmann** [comment]
P.S. Wow -- turns out that ACL2 6.5 back through 5.0 (I didn't test
before that) need the include book, but ACL2 7.0 and the current git
snapshot (and presumably everything inbetween) do not.  So something
changed in 7.0.  It wasn't tau -- 7.0 accepts the events without the
include-book even after (in-theory (disable (tau-system))).

-- Matt

**Comment by nadezhin** [comment]
Can it be caused by pushing `commutativity-2-of-+`, `fold-consts-in-+`, `distributivity-of-minus-over-+` into `axioms.lisp` ?

**Comment by MattKaufmann** [comment]
Yep, that's it!  Indeed, if I first execute

(IN-THEORY (DISABLE FOLD-CONSTS-IN-+))

then that defeats the proof in ACL2 7.0 and the current github version
(and probably everything inbetween).

Thanks --
-- Matt

**Comment by ragerdl** [comment]
Based on the conversation, it sounds like Matt is good with this patch.  So, I'm merging it.  Please let me know if I misunderstand.

**Pull request merged**
