### PR TITLE
Update filesystem books and add IO lemmas

### PR DESCRIPTION
**Pull request by airbornemihir**
I'm not sure who should review the books/std/io/base.lisp changes, but I think it would suffice for @ericsmithkestrel to do so, since he responded to my question on Slack. I decided to follow the (apparent) convention that lemmas about built-in I/O functions go in the base.lisp file while community-defined functions each get their own file in that directory.

### CODE REVIEW

**Comment by ericwhitmansmith** [comment]
Hi, I don't own std, and can't merge pull requests.  But I did take a look.  I  would suggest removing all hyps except the last one of stringp-of-read-file-into-string1.  Otherwise, the changes to std seem good to me.  (You could also make stringp-of-read-file-into-string1 a :type-prescription rule, but I don't feel strongly about that.)  Thanks, Mihir, for contributing this improvement.

**Comment by ericwhitmansmith** [comment]
Responding to Mihir's note about hyps: It may be the case that no hyp individually could be removed (you have to remove them as a group, because they support each other inductively).  Perhaps remove-hyps doesn't handle that case.

**Comment by airbornemihir** [comment]
@ericwhitmansmith : I haven't checked, but this seems plausible to me. I've made @MattKaufmann aware of this discussion about remove-hyps, but I'm tagging him here so he can take your hunch above into account.

**Comment by MattKaufmann** [comment]
@ericwhitmansmith  I like your theory.  In fact I tried removing just one hyp at a time and the proof failed (even without the step-limit restrictions imposed by remove-hyps).  I suppose remove-hyps could be made more powerful by attempting removal of more than one hyp at a time, but that would also slow it down.

@airbornemihir  I've updated :doc remove-hyps by adding a paragraph about this limitation.  The bleeding-edge manual (http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html) is up-to-date with this change.  If you think it's not clear, feel free to change it further or to send me email to work out an improvement.  As far as I'm concerned, case closed. ;)  Of course, feel free to add options to remove-hyps that make it more aggressive.

**Comment by MattKaufmann** [comment]
Oops, I clicked the button prematurely... manual update and git push should happen in a few minutes....

**Comment by MattKaufmann** [comment]
OK, done; sorry about the noise.

**Comment by airbornemihir** [comment]
No problem. Thanks for looking into this, Matt.

**Pull request merged**
