### PR TITLE
Restore rtl/rel11/masc arrays. Use rtl/rel11 in workshop. Remove trai…

### PR DESCRIPTION
**Pull request by nadezhin**
…ling spaces.

@ragerdl , is this simple cert.acl2 enough to support package-aware certification ?

### CODE REVIEW

**Comment by ragerdl** [comment]
@nadezhin Yes, that cert.acl2 file should be enough.

@russinoff Assuming this patch builds, it looks good to me.  However, it's well beyond what we've discussed for auto-approvals, so could you please have a look and advise?

Since the pull request/patch is being applied to the testing branch, I'll know that the patch passes the regression (which includes most workshop books) before the patch makes it into the master branch.

**Comment by russinoff** [comment]
I wish I understood this better.  At some point. Kaufmann commented out the
array section of lib/masc.lisp.  This was unacceptable.  It was decided
that I should use the "misc/records" book instead.  Does that not work with
gl?  Why not?  Is the suggestion that we put the original code back in
lib/masc.lisp?  Is Kaufmann oging to remove it again?  Please explain.

**Comment by MattKaufmann** [comment]
I can answer this part:

>> Is Kaufmann oging to remove it again?

Nope -- I haven't been following this discussion (and I'm on
vacation).

'mu
   Date: Sat, 08 Aug 2015 13:53:28 -0700
   From: russinoff <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>

   I wish I understood this better.  At some point. Kaufmann commented out t=
   he
   array section of lib/masc.lisp.  This was unacceptable.  It was decided
   that I should use the "misc/records" book instead.  Does that not work wi=
   th
   gl?  Why not?  Is the suggestion that we put the original code back in
   lib/masc.lisp?  Is Kaufmann oging to remove it again?  Please explain.

   On Sat, Aug 8, 2015 at 9:30 AM, David L. Rager <notifications@github.com>=

   wrote:

   > @nadezhin <https://github.com/nadezhin> Yes, that cert.acl2 file should=

   > be enough.
   >
   > @russinoff <https://github.com/russinoff> Assuming this patch builds, i=
   t
   > looks good to me. However, it's well beyond what we've discussed for
   > auto-approvals, so could you please have a look and advise?
   >
   > Since the pull request/patch is being applied to the testing branch, I'=
   ll
   > know that the patch passes the regression (which includes most workshop=

   > books) before the patch makes it into the master branch.
   >
   > =E2=80=94
   > Reply to this email directly or view it on GitHub
   > <https://github.com/acl2/acl2/pull/477#issuecomment-128986829>.
   >


   ---
   Reply to this email directly or view it on GitHub:
   https://github.com/acl2/acl2/pull/477#issuecomment-129043826=

**Comment by russinoff** [comment]
Right, but you will be returning. When you did remove the code, it was a
unilateral decision, and things broke without warning.

**Comment by nadezhin** [comment]
Your arrays records have default values 0.
misc/records have default vaue nil.
Can rtl environment work with nil-default records ?

**Comment by MattKaufmann** [comment]
I think the problem (which I don't recall perfectly) was that the
rtl/rel11 books, perhaps lib/masc.lisp in particular, used definitions
of records that conflicted with those in a records book.  When the
top-level manual book attempted to include both, it got a name
conflict (as I recall).

Perhaps a simple solution would be to have two top-level rtl books,
say, top.lisp and top-manual.lisp.  The top-manual.lisp book would
omit the records stuff, and would be what's included in
books/doc/top.lisp.

If necessary I can probably help with this sometime after my return in
September, but if someone else can take care of it, that would be
great.

-- Matt
   Date: Sat, 08 Aug 2015 19:48:59 -0700
   From: nadezhin <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>
   Cc: MattKaufmann <kaufmann@cs.utexas.edu>

   Your arrays records have default values 0.
   misc/records have default vaue nil.
   Can rtl environment work with nil-default records ?

   On Sat, Aug 8, 2015 at 11:53 PM, russinoff <notifications@github.com> wro=
   te:

   > I wish I understood this better. At some point. Kaufmann commented out =
   the
   > array section of lib/masc.lisp. This was unacceptable. It was decided
   > that I should use the "misc/records" book instead. Does that not work w=
   ith
   > gl? Why not? Is the suggestion that we put the original code back in
   > lib/masc.lisp? Is Kaufmann oging to remove it again? Please explain.
   >
   > On Sat, Aug 8, 2015 at 9:30 AM, David L. Rager <notifications@github.co=
   m>
   > wrote:
   >
   > > @nadezhin <https://github.com/nadezhin> Yes, that cert.acl2 file shou=
   ld
   > > be enough.
   > >
   > > @russinoff <https://github.com/russinoff> Assuming this patch builds,=
    it
   > > looks good to me. However, it's well beyond what we've discussed for
   > > auto-approvals, so could you please have a look and advise?
   > >
   > > Since the pull request/patch is being applied to the testing branch, =
   I'll
   > > know that the patch passes the regression (which includes most worksh=
   op
   > > books) before the patch makes it into the master branch.
   > >
   > > =E2=80=94
   > > Reply to this email directly or view it on GitHub
   > > <https://github.com/acl2/acl2/pull/477#issuecomment-128986829>.
   >
   > >
   >
   > =E2=80=94
   > Reply to this email directly or view it on GitHub
   > <https://github.com/acl2/acl2/pull/477#issuecomment-129043826>.
   >


   ---
   Reply to this email directly or view it on GitHub:
   https://github.com/acl2/acl2/pull/477#issuecomment-129096845=

   ----==_mimepart_55c6bf9bd929e_373b3fe2d3b172b82741e0
   Content-Type: text/html;
    charset=UTF-8
   Content-Transfer-Encoding: quoted-printable

   Your arrays records have default values 0.<br>
   misc/records have default vaue nil.<br>
   Can rtl environment work with nil-default records ?<br>
   <br>
   On Sat, Aug 8, 2015 at 11:53 PM, russinoff &lt;notifications@github.com&g=
   t; wrote:<br>
   <br>
   &gt; I wish I understood this better. At some point. Kaufmann commented o=
   ut the<br>
   &gt; array section of lib/masc.lisp. This was unacceptable. It was decide=
   d<br>
   &gt; that I should use the &quot;misc/records&quot; book instead. Does th=
   at not work with<br>
   &gt; gl? Why not? Is the suggestion that we put the original code back in=
   <br>
   &gt; lib/masc.lisp? Is Kaufmann oging to remove it again? Please explain.=
   <br>
   &gt;<br>
   &gt; On Sat, Aug 8, 2015 at 9:30 AM, David L. Rager &lt;notifications@git=
   hub.com&gt;<br>
   &gt; wrote:<br>
   &gt;<br>
   &gt; &gt; @nadezhin &lt;https://github.com/nadezhin&gt; Yes, that cert.ac=
   l2 file should<br>
   &gt; &gt; be enough.<br>
   &gt; &gt;<br>
   &gt; &gt; @russinoff &lt;https://github.com/russinoff&gt; Assuming this p=
   atch builds, it<br>
   &gt; &gt; looks good to me. However, it&#39;s well beyond what we&#39;ve =
   discussed for<br>
   &gt; &gt; auto-approvals, so could you please have a look and advise?<br>=

   &gt; &gt;<br>
   &gt; &gt; Since the pull request/patch is being applied to the testing br=
   anch, I&#39;ll<br>
   &gt; &gt; know that the patch passes the regression (which includes most =
   workshop<br>
   &gt; &gt; books) before the patch makes it into the master branch.<br>
   &gt; &gt;<br>
   &gt; &gt; =E2=80=94<br>
   &gt; &gt; Reply to this email directly or view it on GitHub<br>
   &gt; &gt; &lt;https://github.com/acl2/acl2/pull/477#issuecomment-12898682=
   9&gt;.<br>
   &gt;<br>
   &gt; &gt;<br>
   &gt;<br>
   &gt; =E2=80=94<br>
   &gt; Reply to this email directly or view it on GitHub<br>
   &gt; &lt;https://github.com/acl2/acl2/pull/477#issuecomment-129043826&gt;=
   .<br>
   &gt;<br>


   <p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">&m=
   dash;<br>Reply to this email directly or <a href=3D"https://github.com/ac=
   l2/acl2/pull/477#issuecomment-129096845">view it on GitHub</a>.</p>
   <div itemscope itemtype=3D"http://schema.org/EmailMessage">
     <div itemprop=3D"action" itemscope itemtype=3D"http://schema.org/ViewAc=
   tion">
       <link itemprop=3D"url" href=3D"https://github.com/acl2/acl2/pull/477#=
   issuecomment-129096845"></link>
       <meta itemprop=3D"name" content=3D"View Pull Request"></meta>
     </div>
     <meta itemprop=3D"description" content=3D"View this Pull Request on Git=
   Hub"></meta>
   </div>

   ----==_mimepart_55c6bf9bd929e_373b3fe2d3b172b82741e0--

**Comment by nadezhin** [comment]
Another simple solution is to rename a few conflicting functions in the rtl
library.

**Comment by MattKaufmann** [comment]
Interesting idea; seems plausible.  I expect to be happy with any
solution that is made by someone other than me!

Thanks --
-- Matt
   Date: Sun, 09 Aug 2015 04:58:29 -0700
   From: nadezhin <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>
   Cc: MattKaufmann <kaufmann@cs.utexas.edu>

   Another simple solution is to rename a few conflicting functions in the rtl
   library.

   On Sun, Aug 9, 2015 at 9:05 AM, MattKaufmann <notifications@github.com>
   wrote:

   > I think the problem (which I don't recall perfectly) was that the
   > rtl/rel11 books, perhaps lib/masc.lisp in particular, used definitions
   > of records that conflicted with those in a records book. When the
   > top-level manual book attempted to include both, it got a name
   > conflict (as I recall).
   >
   > Perhaps a simple solution would be to have two top-level rtl books,
   > say, top.lisp and top-manual.lisp. The top-manual.lisp book would
   > omit the records stuff, and would be what's included in
   > books/doc/top.lisp.
   >
   > If necessary I can probably help with this sometime after my return in
   > September, but if someone else can take care of it, that would be
   > great.
   >
   > -- Matt
   > Date: Sat, 08 Aug 2015 19:48:59 -0700
   > From: nadezhin <notifications@github.com>
   > Reply-To: acl2/acl2 <reply@reply.github.com>
   > Cc: MattKaufmann <kaufmann@cs.utexas.edu>
   >
   > Your arrays records have default values 0.
   > misc/records have default vaue nil.
   > Can rtl environment work with nil-default records ?
   >
   > On Sat, Aug 8, 2015 at 11:53 PM, russinoff <notifications@github.com> wro=
   =3D
   > te:
   >
   > > I wish I understood this better. At some point. Kaufmann commented out =
   =3D
   > the
   > > array section of lib/masc.lisp. This was unacceptable. It was decided
   > > that I should use the "misc/records" book instead. Does that not work w=
   =3D
   > ith
   > > gl? Why not? Is the suggestion that we put the original code back in
   > > lib/masc.lisp? Is Kaufmann oging to remove it again? Please explain.
   > >
   > > On Sat, Aug 8, 2015 at 9:30 AM, David L. Rager <notifications@github.co=
   =3D
   > m>
   > > wrote:
   > >
   > > > @nadezhin <https://github.com/nadezhin> Yes, that cert.acl2 file shou=
   =3D
   > ld
   > > > be enough.
   > > >
   > > > @russinoff <https://github.com/russinoff> Assuming this patch builds,=
   =3D
   > it
   > > > looks good to me. However, it's well beyond what we've discussed for
   > > > auto-approvals, so could you please have a look and advise?
   > > >
   > > > Since the pull request/patch is being applied to the testing branch, =
   =3D
   > I'll
   > > > know that the patch passes the regression (which includes most worksh=
   =3D

**Comment by russinoff** [comment]
Dmitry,I think I finally understand the problem and I like your proposal.
Do it.

I just completed a major proof that required a number of extensions to the
library, which I'll check in once your pull request has been granted. (I'm
not looking forward to the merging process.)

**Comment by ragerdl** [comment]
Hi @nadezhin ,

Do you mind please updating your "nadezhin:masc-arrays" branch to contain the changes I made regarding trailing whitespaces?  It's subjective as to whether I did us a favor, but I went ahead and made those changes so it'd be easier to review this patch and see the diffs.

Thanks,
David

**Comment by nadezhin** [comment]
I've updated "nadezhin:masc-arrays" branch.

**Comment by ragerdl** [comment]
It looks like you changed the lib/masc.lisp file, patched up the aforementioned workshop books, and removed a ton of support books.  I believe I have russinoff's approval for the lib masc changes.  As such, I am merging this pull request.  Thanks for cleaning this up -- it looks much better!

**Comment by russinoff** [comment]
I have updated my local repository in order to make a pull request.  I'm
confused because I don't see the changes in the array section of
rtl/rel11/lib/masc.lisp that Dmitry was supposed to have made.  What am I
missing?

**Comment by ragerdl** [comment]
Hi David,

Thanks for the report.  It looks like there may be a bug with the pull
request Dmitry made.  Jenkins seems to have caught the bug and prevented it
from propogating into the master branch, which is what you've checked out:

http://leeroy.defthm.com/job/acl2-testing/103/console

I'll have a look into it.

David

**Comment by russinoff** [comment]
I think I finally understand.  I think the right fix is to stick with
misc/records and define an array accessor that effectively has defsult
vslue 0:

(defun r (a x) (or (g a x) 0)

If that seems ok, then hold off on Dmitry's pull request and let me include
that fix in mine.

**Comment by russinoff** [comment]
I retract my last suggestion regarding the array issue.  Go ahead with
Dmitry's solution.

**Comment by nadezhin** [comment]
David @russinoff,

I agree that keeping multiple variances of records in ACL2 books is inelegant.
By the way, there are yet more records with default 0
in `projects/x86isa/utils/records-0`.
I would like to search for a better solution.

Why did you retract your solution with `r (a x)` ?

I thought about one more solution - a limited support of
default value in misc/records.
Now `(implies (rcdp r) (true-listp r))`.
We could relax this to `(implies (rcdp r) (listp r))`
and consider the atom `(final-cdr r)` as the default value.
However, default value is limited to an atom in this case.
Another drawback that it could break some of misc/records clients.

**Comment by russinoff** [comment]
I abandoned my proposal when I started trying to prove the analogs of the
lemmas in misc/records.  For example, the analog of

(defthm s-same-g
  (equal (s a (g a r) r)
         r))

is not true.

I'd like to settle on a solution soon, because I have a project that
depends on it.

Meanwhile, I think I'll go ahead and issue a pull request for my other
stuff.

**Comment by ragerdl** [comment]
Hi David,

You should now be able to do a "git pull" from within your version of the
master branch and obtain Dmitry's changes from the other day.

David

**Comment by russinoff** [comment]
I shall do so.

**Comment by russinoff** [comment]
OK, I think I just created a pull request.  I would note once again that
the instructions in the on-line documentation are badly broken.  I had to
guess about a few things.

I have another pull request that I'd like to make, to add
books/projects/masc, but first I have a question, which I think was once
answered, but I didn't understand the answer.

What is the recommended way to certify a book that begins with (in-package
"RTL")?  If I try (certify-book "foo") immediately after loading acl2, thrn
of course I get the complaint that the RTL package is unknown.  So instead
I do this:

(include-book "rtl/rel11/lib/top" :dir :system)  ;or some such
(certify-book "foo" 1)

This works, but it seems clumsy.

**Comment by solswords** [comment]
Personally speaking, I rarely certify a book from inside an interactive
ACL2 session.  I use the Makefile from the books directory or else use "
cert.pl bookname" to do it from the command line.  (Cert.pl is located in
books/build and I would suggest symlinking it into your path, or adding
books/build to your path.)

If you want to certify a book from an interactive session, you can manually
replicate what cert.pl automates by
 - certifying all the books that your book includes, using cert.pl or the
Makefile
 - in your interactive session, LDing the .port files of all those books
before certifying your book.  Each of these contains the portcullis
commands of the corresponding book, which in particular will define all of
the packages used by those books.

E.g. if your book includes rtl/rel11/lib/top, then do
(ld "rtl/rel11/lib/top.port" :dir :system)
before your certify-book command.

I would suggest just using cert.pl instead, though -- if only so that once
you succeed in certifying a book, you can be sure of repeating that
success, without having to look through your session to figure out exactly
what you had to do before certifying it.

 - Sol

**Comment by russinoff** [comment]
Thanks.  In the end, I guess to certify a book interactively, I can't do
any better than what I've been doing:

(include-book "rtl/rel11/lib/top" :dir :system)

(certify-book "foo" 1)

If I do this consistently, then I won't have to think about how a book was
certified.

If I try to certify a book after

(ld "rtl/rel11/lib/top.port")

then it wants

(certify-book "foo" 10)

which is a little scary.

**Comment by ragerdl** [comment]
Hi David,

If it's the typing of "10" that you're concerned about, you should be able
to use "?" instead.

David

**Comment by russinoff** [comment]
Right, I don't like typing "10".  This should not seem unreasonable to a
guy who insists on removing a trailing space character as a "hygienic"
measure

But more seriously, is there an advantage of loading top.port over
including top?

And, by the way, did my pull request go through?.

**Comment by solswords** [comment]
Whatever works for you is fine.  But the build scripts (makefile/cert.pl)
will be loading the portfile, and if you want your interactive use of
certify-book to ensure that it'll work when the makefile runs, it'd be
better to emulate what the scripts are going to do.  If you want to emulate
it exactly, you can take a look at the bookname.cert.out file produced by
the build scripts, which contain (at the top) the full set of commands sent
to acl2 to do the certification.

You said using (certify-book "foo" 10) is scary.  I assume that's because
you don't know exactly what those 10 commands are.  But your include-book
is also doing a lot of stuff -- probably a lot more than those 10
commands.  It itself also has a portcullis that probably has several
commands in it -- defpkgs and include-books all sucked in by the build
system.  So in my view, if you're including books that include other books
that define packages etc. etc., you shouldn't also hesitate to go ahead and
do
  (certify-book "book" ?).

 - Sol

**Comment by russinoff** [comment]
I have a directory that I'd like to upload to books/projects/masc.  I'm a
little confused about the business of regression testing.

The directory contains the following subdirectories:

(1) A Flex/Bison parser for the MASC language, which a representation of a
program as a set of S-expressuons

(2) An ACL2 program that converts these S-expressions to an executable ACL2
model of the MASC program

(3) A script that runs the parser, generates the ACL2 model, and some other
stuff.

(4) A couple of simple illustrations, including the imul example that was
described in our 2014 workshop paper, along with the script for the
correctness proof.

So I don't know what it means to test this thing for regression.  I guess
my intention is that an interested party would copy this directory
somewhere and follow my instructions for compiling the parser, running the
examples, and certifying the proof script.

So I copied this directory into my local acl2/books directory and just for
kicks, ran the regression thing.  It failed, and I don't know what this
means.

**Pull request merged**
