### PR TITLE
Enumerators are truely attachable using defdata-attach.

### PR DESCRIPTION
**Pull request by harshrc**
'make acl2s basic' passed, but did not build manual.

### CODE REVIEW

**Comment by ragerdl** [comment]
HI @harshrc , 

Changes look good.  Can you please submit this pull request against the testing branch next time?  I'll recreate the pull request against that for this one.

Thanks,
David

**Comment by harshrc** [comment]
@ragerdl 
I didnt quite understand what you said.
I am just following instructions on Github-commit-code-using-pull-requests. Have those changed?

**Comment by ragerdl** [comment]
@harshrc 
Hmmm, not sure what happened, but I sent out the following email this past day.  Anyway, the instructions are updated in the manual.  What you did is fine -- I just mention the change so that you can take advantage of the "testing" branch in the future.  For example, I didn't ask you to rebuild the manual this time, since the "testing->master release process" will do that anyway.

```
If you've never contributed to our repository via pull requests you
can stop reading now.

I've added one more step to the "pull request model" for contributing
to ACL2 books. This additional step takes advantage of our cloud-based
Jenkins server that ensures that each patch successfully builds the
regression on ccl-based ACL2 (with hons).  After this check is
completed, the patch is automatically saved into the "master" branch
of the repository.  Specifically the following step was added:

3. In the drop-down box labeled "base" (next to the box labeled "base
fork"), change the value from "master" to "testing".
```

**Comment by harshrc** [comment]
nice! thanks @ragerdl

**Pull request merged**
