### PR TITLE
Formalized several self-timed circuit models

### PR DESCRIPTION
**Pull request by myall86**
Added self-timed circuits performing (1) arbitrated merge operations and (2) serial addition/subtraction

### CODE REVIEW

**Comment by airbornemihir** [comment]
Hi Cuong,

You seem to have removed copyright notices from several of your files. 
Is that intended?

Mihir.

**Comment by myall86** [comment]
Hi Mihir,

Yes. Those are just common setup/configuration files so I don't feel like I
need copyright for them.

Thanks,
Cuong

**Comment by ragerdl** [comment]
Technically everything is copyrighted, whether one declares it or not.  Lawyers like to decide what that means, but it helps if there's a stated license for all content.  One could achieve such a statement by putting a LICENSE file with the appropriate license in the `async` directory.

**Comment by myall86** [comment]
Hi David,

Okay. I've added a LICENSE file to the async/ directory. I've also restored
the copyright notices in the setup files.

Thanks,
Cuong

**Comment by MattKaufmann** [comment]
The LICENSE file looks perfect to me, so I'm assuming all is well and I'll accept the pull request now.

**Comment by myall86** [comment]
Thanks, Matt :).

Cheers,
Cuong

**Pull request merged**
