### PR TITLE
Fix formatting in E/D doc topic

### PR DESCRIPTION
**Pull request by kini**
Not sure whether to leave the "[etc]" or make it a "..." like I've seen in most such examples, but there you have it.

### CODE REVIEW

**Comment by kini** [comment]
@MattKaufmann said he preferred "..." on IRC, so I changed it. I also fixed a comment in `books/system/doc/render-doc.lisp`.

**Comment by ragerdl** [comment]
@MattKaufmann This pull request looks fine to me, but I don't want to pollute your doc building process by accident, so I'm going to let you merge this.  Let me know if you want help with that or if it looks good to you and I'll merge it at that point.

**Comment by kini** [comment]
Something's wrong here. I tried doing `make acl2-manual` again but `doc.lisp` in the top level directory didn't actually change to match the comments I made. Also I notice that `doc.lisp` in the top level directory is tracked in git and seems to be getting updated by @MattKaufmann from time to time. If it's really an autogenerated file, why is it tracked in git? I must be missing something.

**Comment by kini** [comment]
Never mind, I gather from a conversation on IRC that `doc.lisp` is autogenerated but not by the `make acl2-manual`, and so I guess I won't worry about it. At the very least, the edit I made to `render-doc.lisp` is not *wrong*, so...

**Comment by MattKaufmann** [comment]
Just to explain a bit about doc.lisp:

It's part of the ACL2 system (defined to be: everything that is not
under books/).  So it's "editable" only by J and me.  In practice,
it's "edited" by a suitable "make" command that I issue, to bring it
up to date with books/system/doc/acl2-doc.lisp.  From time to time, I
commit doc.lisp, using with a message saying something like "synching
up doc.lisp".  Note that I do my updates with the script bin/pull.sh,
to guarantee that nobody other than me or J touches the ACL2 system.

I definitely don't want to change this doc.lisp practice.  I realize
that it's unusual to commit an auto-generated file, but the process
seems to be working rather flawlessly (except for the confusion
understandably expressed by Keshav, which I hope this clears up).
With this practice, we are allowing :doc to be run at the terminal to
get ACL2 system documentation, without the need to include any books.

-- Matt
   Date: Wed, 04 Mar 2015 08:32:32 -0800
   From: Keshav Kini <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>
   Cc: MattKaufmann <kaufmann@cs.utexas.edu>


   Something's wrong here. I tried doing `make acl2-manual` again but `doc.lisp` in the top level directory didn't actually change to match the comments I made. Also I notice that `doc.lisp` in the top level directory is tracked in git and seems to be getting updated by @MattKaufmann from time to time. If it's really an autogenerated file, why is it tracked in git? I must be missing something.

   ---

**Comment by MattKaufmann** [comment]
Nice fixes; thanks, Keshav.

**Comment by kini** [comment]
Perfect, thanks for the explanation, Matt. I didn't mean to suggest we change this practice, I was just a little confused. Luckily my fix only involved changes to files in `books/` so I guess we have nothing to worry about. I presume that the next time you sync up `doc.lisp`, the paths in the comments will be corrected.

**Comment by MattKaufmann** [comment]
Thanks, Keshav.  I've synched up doc.lisp (commit 3f4b690df5c3f5113cb902aa082702e81cb9707c).

**Pull request merged**
