### PR TITLE
Update linkes from RTL section of ACL2 manual to online RTL manual

### PR DESCRIPTION
**Pull request by nadezhin**
Synchronize `doc.lisp` with current online manual.
Uncomment `defsection-rtl` in `reps.lisp` .
Insert naive `defsection-rtl` into `excps.lisp` and `masc.lisp` .

### CODE REVIEW

**Comment by ragerdl** [comment]
@russinoff These all look like good changes to me.  Given you're more familiar with the recent changes to libman, do these look approximately correct to you?

**Comment by russinoff** [comment]
Yes, it looks right.

**Comment by ragerdl** [comment]
This was merged into master instead of testing, so people may want to hold off on updating their books until I sound an all-clear.

**Comment by ragerdl** [comment]
All clear -- the master branch built successfully.

**Pull request merged**
