### PR TITLE
Added theorem about sets as lists.

### PR DESCRIPTION
**Pull request by acoglio**

### CODE REVIEW

**Comment by ragerdl** [comment]
Thanks for the suggestion.  May I ask, do all of the books build with this change incorporated?

**Comment by acoglio** [comment]
Yes, the regression succeeded after the change.

**Comment by jaredcdavis** [comment]
Perhaps it would be better to instead prove:

```
(defthm set-equiv-of-nil
  (equal (set-equiv nil x)
         (atom x))
  :hints(("Goal" :in-theory (enable set-equiv))))
```

This would combine nicely with `std/lists/append:consp-of-append` to prove your theorem, but would also be more generally applicable.  I haven't tried a regression with it yet, though.

**Comment by acoglio** [comment]
That seems like a good idea. I’ve replaced ours with yours and successfully run the regression. I believe that this new commit has become part of the outstanding pull request, but I’m not a github expert so please let know if that’s not the case.

**Comment by jaredcdavis** [comment]
Looks good to me -- thanks for running the regression.  Merging.

Cheers,
Jared

**Pull request merged**
