### PR TITLE
Clarify the use of state in read-file-into-string

### PR DESCRIPTION
**Pull request by airbornemihir**
This is explained in :doc programming-with-state, of course, but
personally I found it unintuitive why state needs to be declared as a
stobj when it doesn't appear in the "text" of a call to
read-file-into-string (thanks to macro expansion), and I had to look up
examples of the use of this function in the community books to be sure.

Please feel free to improve the language before merging.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
Thanks, Mihir, for suggesting documentation changes.  I like the basic
idea you've put forward.  To summarize: Where the documentation said
that "the expansion of a call of this macro takes @('state') as an
argument", there is the following proposed new sentence.

    The expansion of a call of this macro does take @('state') as an
    argument, which necessitates either the evaluation of
    (set-state-ok t), or the declaration of state as a @(tsee stobj)
    (see :@(tsee programming-with-state)).

I see the point: since state isn't lexically visible, more explanation
is perhaps called for.  Still, I'd like to make it clear that this is
just as usual for state.  Also, I don't want to point to :doc
programming-with-state, which is a long topic that isn't necessary for
understanding read-file-into-string; and I don't want to link to
stobj, since only state is involved here, so stobjs are a distraction.
And finally, I'd like to link to :doc xargs for the :stobjs declaration.

I don't know how to modify pull requests, but I plan to make the
following change myself this afternoon (I'm doing other testing
anyhow).  If nobody stops me and that goes through, then I guess we
should close this pull request.

    Note that the expansion of a call of this macro takes @('state')
    as an argument, which (as usual for functions that take
    @('state')) necessitates either that @('(set-state-ok t)') has
    already been evaluated, or else that a suitable @(':stobjs')
    declaration, typically @(':stobjs state'), is provided (see @(see
    xargs)).

**Comment by airbornemihir** [comment]
Thanks, Matt.

**Comment by airbornemihir** [comment]
I realise not everyone wants to do it this way, but here are some 
instructions for editing a pull request on the command line, summarised 
from here 
(https://help.github.com/articles/checking-out-pull-requests-locally/). 
One would want to fetch the pull request locally

$ git fetch origin pull/846/head:/local-copy/

make some changes (replacing dd with one's favourite text editor)

$ dd if=/dev/random of=books/system/doc/acl2-doc.lisp 
<https://github.com/acl2/acl2/pull/846/files#diff-19702f00ffe842f61ede3818a5cd8124>

commit them

$ git commit -m "Improve documentation language"

merge one's changes, probably after pulling from origin/testing

$ git merge testing

switch to testing

$ git rebase local-copy testing

and push to the testing branch.

$ git push

I hope this is helpful!

Mihir.

**Comment by MattKaufmann** [comment]
Closing this pull request, which I've dealt with in commit f824b54557e4aa923f05d78a012a0916e0aaed0c.

**Pull request closed without merging**
