### PR TITLE
Shnf: parameterized by subring of complex numbers

### PR DESCRIPTION
**Pull request by nadezhin**
Functions and theorems in `shnf/support.lisp`  are parameterized by subring of complex number.
`shnf\top.lisp` is almost without changes.

### CODE REVIEW

**Comment by ragerdl** [comment]
Nice, @russinoff What do you think?

**Comment by russinoff** [comment]
@nadezhin I think it's great that you have found a use for the shnf book and that you have extended it to a more general class of rings.  It's important to me, however to retain the simpler version, and in particular, the original definition of evalh-witness without reference to the complex numbers, which is consistent with my provincial view of the ACL2 world and the very primitive theory that is the basis of all of my work.  Would it be possible to leave shine/top intact and include a separate function (in shnf/support) for the complex case?

**Comment by nadezhin** [comment]
@russinoff, I returned your integer code. It is in the first part of `support.lisp`. The second part of `support.lisp` contains generic code with only `real/rationalp` and `acl2-numberp` instantiations.

**Comment by nadezhin** [comment]
Work on rational polynomials became less important for me. I withdraw this pull request until I or  somebody need rational polynomials again.

**Pull request closed without merging**
