### PR TITLE
New completeness theorem in shnf.

### PR DESCRIPTION
**Pull request by russinoff**

### CODE REVIEW

**Comment by russinoff** [comment]
Proved the completeness theorem for sparse Horner normal forms in books/projects/shnf:
If two polynomials have the same value for every set of variable assignments, then they produce the same normal form.

**Comment by ragerdl** [comment]
Awesome!  I'll open another pull request that requests a merge into testing.

**Comment by russinoff** [comment]
Please explain.  Did I do something wrong.  Is there something else I
should have done?

**Comment by ragerdl** [comment]
Hi David,

You happened to miss Step 3 under the heading "Contribute Your
Changes" at http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/?topic=ACL2____GITHUB-COMMIT-CODE-USING-PULL-REQUESTS
.  No big deal, but it's good to use the testing branch to test
commits before (automatically) merging those commits into the master
branch, so that the master branch is more stable.

Thanks,
David

**Pull request closed without merging**
