### PR TITLE
Proof of the Schröder-Bernstein theorem

### PR DESCRIPTION
**Pull request by gjurgensen**
A proof of the Schröder-Bernstein theorem, which states that when there exists an injection from A to B, and another from B to A, then there exists a bijection between A and B.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
@gjurgensen Would you be willing to add copyright and license information, either via comments added to each of your books or else a LICENSE file?  (You can find examples in the community books, or feel free to ask for help.)  Thanks.

**Comment by russinoff** [comment]
Grant, this is an important contribution.  If you haven't already done so,
would you please notify ***@***.*** ?

**Comment by MattKaufmann** [comment]
Thanks, @gjurgensen !  Merging now.

**Comment by gjurgensen** [comment]
> Grant, this is an important contribution. If you haven't already done so, would you please notify \*\*\*@\*\*\*.\*\*\* ?

@russinoff I'm seeing asterisks instead of an e-mail address. Who was it that you'd like me to notify?

**Comment by russinoff** [comment]
Strange. Freek Wiedijk is the guy who maintains the Web site "Formalizing
100 Theorems".  ***@***.***

**Pull request merged**
