### PR TITLE
adding artifacts for paper: Verification of GossipSub in ACL2s

### PR DESCRIPTION
**Pull request by ankitku**

### CODE REVIEW

**Comment by ankitku** [comment]
make.sh certifies relevant ACL2s files

**Comment by MattKaufmann** [comment]
@ankitku Certification failed.  Would you please arrange that your books certify in ACL2, not just ACL2s?  I think maybe @maxvonhippel, @mister-walter, or @pmanolios can help with that.  In the meantime, you could add a file cert_pl_exclude in your new directory so that the testing branch is no longer broken.

**Comment by maxvonhippel** [comment]
Working on it.

**Comment by maxvonhippel** [comment]
Ok, [I think I fixed it](https://github.com/acl2/acl2/pull/1551).  Please try my version and see if it works.  Thanks!

**Pull request merged**
