### PR TITLE
Update to quicklisp as of June 4, 2020

### PR DESCRIPTION
**Pull request by ragerdl**
Updated to the latest quicklisp libraries.

Followed instructions at https://github.com/acl2/acl2/wiki/How-to-update-quicklisp, using SBCL

### CODE REVIEW

**Comment by ragerdl** [comment]
Kaufmann writes out of band, "The "everything" regression completed without error in a typical
amount of time."

The regression mostly built for me on SBCL -- the errors I saw were related to not having an SBCL with the right compilation flags installed.

At this point, we've done more work than usual to check the correctness (usually I just do CCL), so I'm going to fix it to point to testing and merge.

**Comment by ragerdl** [comment]
Hmm, I'll give it the rest of the day for someone to object to me updating quicklisp.  I doubt anyone will, though, so I plan to merge it eagerly.

**Comment by kini** [comment]
The diff is too large to feasibly review (IMO) so the fact that there was no negative impact on the regression is more than good enough to merge this, in my opinion.

**Comment by ragerdl** [comment]
In addition to just wanting to get it done, I'm trying to get it in while the leeroy builds are stable.  So, I'll go ahead and merge it.

**Comment by shigoel** [comment]
A tad late but here it is: I've got macOS Catalina 10.15.5 and CCL (v1.12-4-g579ed109). Regression done successfully.

**Comment by ragerdl** [comment]
This makes me feel better, thanks @shigoel !  (and Matt and Kini!)

**Pull request merged**
