### PR TITLE
Fix CI issues + typo

### PR DESCRIPTION
**Pull request by maxvonhippel**
See [this discussion](https://github.com/acl2/acl2/pull/1544#issuecomment-1753929923)

### CODE REVIEW

**Comment by MattKaufmann** [comment]
@maxvonhippel Would you change this to merge into master instead of testing, please?  (Sorry, I don't know how to do that myself.)

**Comment by MattKaufmann** [comment]
@maxvonhippel Sorry, I meant merge into testing instead of master.

**Comment by acoglio** [comment]
I changed the base to testing.

**Comment by maxvonhippel** [comment]
Thanks @acoglio !

**Comment by MattKaufmann** [comment]
@maxvonhippel Just an idea (please ignore if it's off-base): I wonder if you could get your books (except the ACL2(r) book) to certify without ACL2s by including some books under `books/acl2s/` (possibly in .acl2 files, if that's necessary because of package issues).

**Comment by maxvonhippel** [comment]
I suspect the answer is yes, and plan to consult with Pete tomorrow
morning about what the minimal such solution is.  But if you have a
concrete suggestion I'm happy to try it!  

Note, I've been a little flummoxed in my efforts to work on this because
the recent Mac OS update broke my SBCL install, and then when I tried to
rebuild ACl2s, I ran into significant issues with QuickLisp.  This
happens pretty much every time on M1 and the only solution I've found is
to purge QuickLisp from all the top.lisp files, but I haven't had time
to comprehensively do so on my local install.  Hopefully I can finish my
hacky fix tonight, and then figure out how to get the certification
working.

best,

Max

On October 9, 2023, znguyenVAS ***@***.***> wrote:
> @maxvonhippel <https://github.com/maxvonhippel> Just an idea (please
> ignore if it's off-base): I wonder if you could get your books (except
> the ACL2(r) book) to certify without ACL2s by including some books
> under books/acl2s/ (possibly in .acl2 files, if that's necessary
> because of package issues).
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1545#issuecomment-1754004480>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABDXNM2RB4VCFM6FHHEGQXTX6R4LBAVCNFSM6AAAAAA5ZNK6W6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJUGAYDINBYGA>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Pull request merged**
