### PR TITLE
Got the ACl2s stuff to certify

### PR DESCRIPTION
**Pull request by maxvonhippel**
With some help from Pete, I got the ACl2s scripts in my workshop book to certify, in this PR.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
@maxvonhippel Thanks for dealing with this.  Please change the pull request to merge into testing instead of master.  (By the way, github sent an email showing removal of a bunch of files, but I think all is well according to "Files changed" on the pull request page.)

**Comment by maxvonhippel** [comment]
Fingers crossed it works this time!

On October 10, 2023, znguyenVAS ***@***.***> wrote:
> Merged #1547 <https://github.com/acl2/acl2/pull/1547> into testing.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1547#event-10606948609>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABDXNMYGPRY3PTUGD4EWZWLX6V2MHAVCNFSM6AAAAAA52O7BDWVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJQGYYDMOJUHA3DAOI>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by maxvonhippel** [comment]
Ok @MattKaufmann I can work on debugging this.  For my benefit, can you tell me, is the `testing` branch at least passing now?  Or am I still blocking everyone from making their own changes, and thus should prioritize getting this done ASAP?

If I'm not blocking, I might wait a few days before getting this done, but if I am blocking, I will try to figure it out tonight.

**Comment by MattKaufmann** [comment]
@maxvonhippel No hurry at all -- your stuff passed testing and is in master now, and based on my own testing I see no short-term problem in master.  When you have time to fix this, that would be great since until then, only the one ACL2(r) book will be getting tested.

**Comment by MattKaufmann** [comment]
@maxvonhippel Actually, it's even less urgent -- let's see if I can get it right this time (sorry about the churn).  With ACL2, all books except the expected exception are being tested.  With ACL2(r), none of your books are being tested by "make regression".  So it's only ACL2(r) regressions that would benefit from your further attention, and even those aren't broken -- they're just skipping all your workshops books.  So, no hurry as far as I'm concerned.

**Comment by maxvonhippel** [comment]
Awesome, thanks!  I’ll take a look when I get a chance then and I’ll
advise Ankit to use my recipe when submitting his book in the next few
days 

On October 10, 2023, znguyenVAS ***@***.***> wrote:
> @maxvonhippel <https://github.com/maxvonhippel> Actually, it's even
> less urgent -- let's see if I can get it right this time (sorry about
> the churn). With ACL2, all books except the expected exception are
> being tested. With ACL2(r), none of your books are being tested by
> "make regression". So it's only ACL2(r) regressions that would benefit
> from your further attention, and even those aren't broken -- they're
> just skipping all your workshops books. So, no hurry as far as I'm
> concerned.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1547#issuecomment-1756288968>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABDXNM7ANA6OFZCDVL3HJ63X6W4R7AVCNFSM6AAAAAA52O7BDWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJWGI4DQOJWHA>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by ericwhitmansmith** [comment]
I just fixed this.  The problem was the directory-wide cert.acl2 file not being compatible with acl2r.   See:
https://github.com/acl2/acl2/commit/c964a53e93c0e8d9f704462461fd4ff18917c088

**Comment by maxvonhippel** [comment]
Fantastic, thank you Eric!  I should have thought of that.

On October 10, 2023, znguyenVAS ***@***.***> wrote:
> I just fixed this. The problem was the directory-wide cert.acl2 file
> not being compatible with acl2r. See:
>  c964a53
> <https://github.com/acl2/acl2/commit/c964a53e93c0e8d9f704462461fd4ff18917c088>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1547#issuecomment-1756484595>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABDXNM5SARPFQG5ETQ4DGA3X6XPALAVCNFSM6AAAAAA52O7BDWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJWGQ4DINJZGU>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Pull request merged**
