### PR TITLE
Update books/rtl/, books/projects/rac/, books/projects/arm/, books/projects/srt/

### PR DESCRIPTION
**Pull request by russinoff**
rtl and arm: Minor modifications and additions in order to satisfy various claims made in my forthcoming Springer book.

rac: Deleted CtoS mode, which is no longer used, as well as support for SystemC register classes, which have been replaced with Algorithmic C registers.  Modified examples/imul accordingly.

srt: This was formerly the book "rtl/rel11/srt", which has been replaced by a simpler version of SRT division and square root.

### CODE REVIEW

**Comment by ragerdl** [comment]
Sweeeeet.  Since the build was broken most of yesterday, and it'd be nice to keep it stable today, I'll ask the annoying question of, were you were able to build the manual with all of these (great) changes?

**Comment by russinoff** [comment]
Huh?  I don't know or even what it means to "build the manual". I suppose
it has something to do with that "defection" stuff that someone inserted in
rt./rel11/lib/, which has not changed.

**Comment by ragerdl** [comment]
Did you run the following command, as specified in the instructions?
```
(time nice make -j 8 regression-fresh) >& make-regression.log
```

**Comment by russinoff** [comment]
Yes.

**Pull request merged**
