### PR TITLE
Adding two regression tests to SV cosims:

### PR DESCRIPTION
**Pull request by arbrock**
This is a pull request for a pair of cosim regressions I've written:
  - _regfile_ ensures arrays are indexed in the correct order: designed to detect bug #399 
  - _nested_ detects a bug in handling of else statements.
At present _nested_ does not pass. I hope these are useful: please merge them whenever it is appropriate.

Thank you,
Andrew

### CODE REVIEW

**Comment by ragerdl** [comment]
@solswords @jaredcdavis 

Is it okay to have cosim regression test that's currently failing as part of the repository?  If so, I'll merge this.

**Comment by solswords** [comment]
AFAIK nobody's depending on that makefile building successfully, but I'd rather there not be failing tests in there with no plans for a fix.  (We should probably have some tests that "pass" by failing the right way, but we don't have this set up yet.)  I'll merge this for now & check on what the problem is.

**Comment by solswords** [comment]
This is fixed; it turned out that in some cases IF tests (and other similar expressions) were getting translated to svex extended with Xes rather than correctly sign or zero-extended.

**Comment by solswords** [comment]
BTW, in SystemVerilog if/then/else statements have truly horrible X behavior:
 if (1'bX) is the same as if (1).  VL/SV is not going to support this particular travesty, which means some cosim tests need to have binary-only inputs.  I changed that "nested" test's inputs.data file so that this is the case.

**Pull request merged**
