### PR TITLE
Add book for "A Case Study in Analytic Protocol Analysis in ACL2"

### PR DESCRIPTION
**Pull request by maxvonhippel**

### CODE REVIEW

**Comment by solswords** [comment]
Thanks! I've changed the destination branch from master to testing.  One other thing -- would you add a line to workshops/2023/README to associate your paper with this new directory (see the entry for Advances in ACL2 Proof Debugging Tools for example).

**Comment by maxvonhippel** [comment]
Done.  @solswords please note, the acl2r script can only be certified using acl2r.  If there is some automated certification of books that happens, this should be taken into account when setting that up.  I'd be happy to help in any way I can!

**Comment by MattKaufmann** [comment]
@maxvonhippel I'll accept and then, after your work gets into master, I'll run an ACL2(r) regression myself (happy to do so, as I haven't done it in awhile).

**Comment by MattKaufmann** [comment]
@maxvonhippel The testing branch is broken.  Would you fix this, please?  I think maybe a .acl2 file is missing.

**Comment by maxvonhippel** [comment]
Yes.  I noticed a typo in the RFC lisp file, which I've fixed on my master branch, but I wasn't able to figure out how to get cert.pl to certify the ACL2s stuff without me needing to specify which ACl2 to use manually, so I've emailed Pete and Ankit for guidance on this front.  I think you're right that I'll need some .acl2 file(s), and perhaps other artifacts as well, to make it all work automatically.

**Comment by ericwhitmansmith** [comment]
Do the books certify with regular (non-s) ACL2?

**Comment by maxvonhippel** [comment]
`a-n-0-acl2.lisp` does.  `a-n-0-acl2r.lisp` , requires ACL2r.  The others require ACL2s.  

I just spent an hour trying to work out how to get the ACL2s scripts to certify with cert.pl and didn't work it out.  I can't spend more time on it right now as I have work obligations, but I can revisit this problem later this evening and tomorrow morning.

All the ACL2s scripts work when run interactively in emacs with an ACL2s prompt and, at some point, I did successfully certify all of them with `certify-book` in order to get the times reported in a table in the paper.

**Comment by maxvonhippel** [comment]
For now, if this is causing issues with your CI, I suggest simply rolling back the merge.  I can cut a new PR once I've worked out the CI issues so that all the code runs in an automated fashion with your build process.

**Comment by ericwhitmansmith** [comment]
An easy temporary fix would be to rename the .lisp files to have .lsp extensions, so ACL2 doesn't try to certify them.

**Comment by ericwhitmansmith** [comment]
The ACL2r books should each include a comment like this:
; cert_param: (uses-acl2r)

**Comment by maxvonhippel** [comment]
Yes, the ACL2r book has that.

I'm fine with the temporary fix you suggested; should I open a new PR
with it + the typo fix I alluded to in the RFC4962 file?

Max

On October 9, 2023, znguyenVAS ***@***.***> wrote:
> The ACL2r books should each include a comment like this:
>  ; cert_param: (uses-acl2r)
>

—
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1544#issuecomment-1753962835>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABDXNMZRCHD7B6YVGDKV7ELX6RZCNAVCNFSM6AAAAAA5TVAIRGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJTHE3DEOBTGU>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by ericwhitmansmith** [comment]
Sounds good to me, thanks.

**Comment by maxvonhippel** [comment]
Ok, [done](https://github.com/acl2/acl2/pull/1545)

**Pull request merged**
