### PR TITLE
Utilities to query defun-sk's.

### PR DESCRIPTION
**Pull request by acoglio**
Utilities to recognize functions introduced via defun-sk and to retrieve their
defun-sk-specific constituents.

### CODE REVIEW

**Comment by ragerdl** [comment]
Nice documentation.  We should probably start including some of these books in the manual.

**Comment by MattKaufmann** [comment]
Absolutely!  Has anyone written a utility to find books that define
doc topics but aren't included (even indirectly) in
books/doc/top.lisp?  If not, would this be a good idea, and are there
any volunteers?

-- Matt

**Comment by acoglio** [comment]
I believe that the documentation in these files that I've just committed get included into the ACL2+Books manual, because I had previously added an entry to include books/kestrel/top in books/doc/top. I hope that doing that was okay; I assumed so, since the pull request was accepted. The Kestrel Books documentation is directly under the software-verification topic, based on previous discussions with Matt.

**Comment by ragerdl** [comment]
Hi Alessandro,

Ah yes, I had forgotten that you had added that entry.  Nicely done!

David

**Pull request merged**
