### PR TITLE
Added imul.lisp back to books/projects/rac/examples/imul/

### PR DESCRIPTION
**Pull request by myall86**
Added imul.lisp back to books/projects/rac/examples/imul/

### CODE REVIEW

**Comment by ragerdl** [comment]
@myall86 This can't be merged -- could you please resolve the conflicts?  Thanks!

**Comment by myall86** [comment]
@ragerdl Resolved. Thanks.

**Comment by ragerdl** [comment]
@myall86 the file wasn't actually added :/

**Comment by myall86** [comment]
@ragerdl Do you mean the conflicted file README wasn't added? I'm not sure what the problem is. I did try to resolve the conflict and merge. Any idea how to solve the problem? Thanks.

**Comment by myall86** [comment]
@ragerdl I had removed imul.lisp in my #1113 commit, but already added back in the #1114 commit.

**Comment by ragerdl** [comment]
@myall86 I expected to see a new file named `imul.lisp` in https://github.com/acl2/acl2/pull/1114/files

**Comment by myall86** [comment]
It's strange. I saw that file was added in
https://github.com/acl2/acl2/commit/1dc70a5a3e3b6ecdcdc9a422b5cc60fab7c0d536.

**Pull request merged**
