### PR TITLE
Update filesystem books

### PR DESCRIPTION
**Pull request by airbornemihir**
No other books are changed.

### CODE REVIEW

**Comment by airbornemihir** [comment]
I seem to have made this pull request against the wrong branch, sorry. Please merge into testing.

**Comment by ragerdl** [comment]
@airbornemihir I think the right thing to do is to close this pull request and resubmit it against testing.

**Comment by solswords** [comment]
Hey @ragerdl  you can also click the Edit button up next to the header and change the branch to merge into, I can do that if there's no further objection.

**Comment by airbornemihir** [comment]
Thanks @solswords @ragerdl .

**Pull request merged**
