### PR TITLE
Add some lemmas for combine16u and combine32u

### PR DESCRIPTION
**Pull request by airbornemihir**
It's not often that we add lemmas with this kind of heavy use of the proof-builder to the community books. However, the need for these lemmas came up while I was working on my own books, and I was surprised that they didn't already exist. So, I hacked them together using the proof-builder, and I'm submitting this pull request to ask if there's interest in having them in this book - if there is, then I'd think it's worth the trouble to make them go through without proof-builder assistance. Also, I'm not currently using combine16s, combine32s, combine64s and combine64u, but I could imagine formulating versions of these lemmas for these functions, for the sake of completeness. So it would also be good to know if anyone would like to help with this additional task.

@jaredcdavis , as the original author of this book, may be interested.

### CODE REVIEW

**Comment by jaredcdavis** [comment]
Hi,

I suspect the bitops library could help with these?  For instance, I
seem to be able to prove your first theorem with just:

(local (include-book "centaur/bitops/ihsext-basics" :dir :system))

(local
 (defthm logior-ash-loghead-logtail
   (implies (and (integerp i) (natp size))
            (equal (logior (ash (logtail size i) size)
                           (loghead size i))
                   i))
   :hints(("Goal" :in-theory (enable* ihsext-recursive-redefs
                                      ihsext-inductions)))))

Cheers,
Jared

On Sun, Sep 23, 2018 at 11:41 AM, airbornemihir
<notifications@github.com> wrote:
> It's not often that we add lemmas with this kind of heavy use of the
> proof-builder to the community books. However, the need for these lemmas
> came up while I was working on my own books, and I was surprised that they
> didn't already exist. So, I hacked them together using the proof-builder,
> and I'm submitting this pull request to ask if there's interest in having
> them in this library - if there is, then I'd think it's worth the trouble to
> try to make them go through without proof-builder assistance. Also, I'm not
> currently using combine16s, combine32s, combine64s and combine64u, but I
> could imagine formulating versions of these lemmas for these functions, for
> the sake of completeness. So it would also be good to know if anyone would
> like to help with this additional task.
>
> ________________________________
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/acl2/acl2/pull/883
>
> Commit Summary
>
> Add some lemmas
>
> File Changes
>
> M books/std/io/combine.lisp (125)
>
> Patch Links:
>
> https://github.com/acl2/acl2/pull/883.patch
> https://github.com/acl2/acl2/pull/883.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Jared C. Davis <jared.c.davis@gmail.com>
11410 Windermere Meadows
Austin, TX 78759
https://www.kookamara.com/jared/

**Comment by ragerdl** [comment]
@airbornemihir In your own book( i.e., not the one that's part of this pull request), when you remove these lemmas, instead including `centaur/bitops/ihsext-basics`, do your proofs still go through?

**Comment by airbornemihir** [comment]
Hi David,

I'm not sure why they should, given that my proofs require the rewriting 
of terms which look like (combine16u ...) and (combine32u ...), and 
these two definitions disabled by default. Are you perhaps suggesting I 
enable these definitions throughout my book?

Mihir.

**Comment by ragerdl** [comment]
Okay, I think I understand well-enough to justify merging this commit.

Basically, this book `combine.lisp` defines some combineXX[u/s] functions.  Reasoning about use of those functions requires the `centaur/bitops/ihsext-basics` book.  So, my question was, "what happens if you just include the `ihsext-basics` book?  I wasn't aware that the combineXX[u/s] functions were defined in `combine.lisp`.  Given they are defined there and appropriately disabled, it seems appropriate to beef up the lemmas about them.

Furthermore, the exported lemmas are hung off very particular uses of `combine16u` and `combine32u`, so they should be cheap to add to users' sessions.

Thanks for the contribution and being willing to go through the social process of convincing others that the changes are good!

**Comment by airbornemihir** [comment]
Hi David,


On Thursday 27 September 2018 11:20 AM, David L. Rager wrote:
>
> Furthermore, the exported lemmas are hung off very particular uses of 
> |combine16u| and |combine32u|, so they should be cheap to add to 
> users' sessions.
>
That's true. The non-local theorems in this PR are basically inversion 
(or invertibility) lemmas for combine16u and combine32u. There were two 
ways to write them out in terms of loghead and logtail, and it looks 
like I have, by chance, chosen the one which is incompatible with 
part-select (see :doc part-select). Maybe I'll fix this later so they 
can be a little more useful for others.
>
> Thanks for the contribution and being willing to go through the social 
> process of convincing others that the changes are good!
>
Of course.

Mihir.

**Pull request merged**
