### PR TITLE
Guards for getters and recognizers of rtl/reps

### PR DESCRIPTION
**Pull request by ragerdl**
Add guards to some of the rtl lib functions.

I'm making this pull request to enable feedback from David Russinoff.  To the admins: please do _not_ merge this pull request.

### CODE REVIEW

**Comment by ragerdl** [comment]
Russinoff has some changes he's going to commit before we merge in these changes.  @nadezhin please let me know if waiting a week to merge these changes will be a problem.

**Comment by nadezhin** [comment]
Additional commits to this pull request:
* merge my changes with David Russinoff's changes.
* clear executable mode on text files
* Weaken hyp from `rationalp` to `real/rationalp` in `rtl/rel11/support/basic.lisp:minus-fl`

**Comment by ragerdl** [comment]
@russinoff Could you please look at the changes by clicking on "files changed" above (in the github interface) and state your approval?  If you have feedback for Dmitry, please provide it.  FWIW, it looks to me to be the union of the guidelines we agreed upon and the changes you and I looked over last Thursday.  Thus, I think it is fine to merge, but I want to check one last time.

**Comment by russinoff** [comment]
It looks fine.  But what does "File mode changed" mean?

**Comment by ragerdl** [comment]
In this case, some of the text/lisp files have executable permissions.  Dmitry has removed those.

**Comment by russinoff** [comment]
OK.

**Pull request merged**
