### PR TITLE
Data-Loop-Free Self-Timed Circuit Verification

### PR DESCRIPTION
**Pull request by myall86**
Added the modeling and verification of several data-loop-free self-timed circuits

### CODE REVIEW

**Comment by kini** [comment]
Please reroll this without the `.DS_store` file.

**Comment by kini** [comment]
Rather than creating a new commit which deletes `.DS_store`, please recreate the original commit without the addition of the file. Adding a file and then deleting it means that the file will still remain in the repository history and add to the amount of data that everyone must download when cloning the repository.

**Comment by myall86** [comment]
Hey Keshav,

I'm not sure what you mean by saying "recreate the original commit without
the addition of the file". Could you send the instruction how to do it?

Thanks,
Cuong

**Comment by airbornemihir** [comment]
man 1 git-rebase has instructions. This is just in case Keshav doesn't
reply with more precise instructions, which he probably will.

Mihir.

**Comment by kini** [comment]
I did it for you -- it's in a branch called `cuong-pull-request` on my github fork of the acl2 repository. Please change your branch to it as follows:

```
git status # check that everything looks normal, i.e. no uncommitted changes
git checkout master # if you're not already on master
git fetch https://github.com/kini/acl2.git cuong-pull-request
git reset --hard FETCH_HEAD
git push -f
```

**Comment by kini** [comment]
And yes, as Mihir says, next time you can do it yourself using `git rebase --interactive`, which is how I did it. (I used the "squash" command within the interactive rebase to squash together your two commits, which made the `.DS_store` file go away from the history.)

**Comment by myall86** [comment]
Thanks.

Cheers,
Cuong

**Comment by kini** [comment]
Someone will probably ask you to add copyright and license information. I see that at the top of your files you have your name and a date. Can you change that to say something like "Copyright (C) Cuong Chau, November 2017" (or whatever date), and then in the README file add a statement saying that your code is licensed under, for example, a BSD 3-clause license? (Or whatever license you like, but I think we tend to prefer BSD 3-clause or MIT/X11.)

**Comment by ragerdl** [comment]
Yes, please add a license to the files.  Thanks!

**Comment by airbornemihir** [comment]
I'll add to Keshav's prediction: next, someone will tell you about the 
background, that books distributed off UT Austin servers (in this case, 
all the community books) are required to have either a 3-clause BSD 
licence, or a GPLv2 licence, which was determined after Matt talked to 
the university lawyers. After that, someone will probably note that your 
books are most likely to be used by folks in industry if you choose the 
3-clause BSD licence :P

(I'm being facetious in my tone but I'm honestly trying to help - this 
comes from discussions I've had about my own books, so you might wanna 
think about these issues sooner rather than later.)

Mihir.

**Comment by kini** [comment]
The community books are not distributed off UT Austin servers, which is why the ACL2 website doesn't provide full tarball downloads of ACL2 and instead points people to github. There are definitely community books in this repository which are not licensed under 3-clause BSD or GPLv2, such as the large number of MIT/X11 books... but even if you exclude those, there are some files in the repo with other idiosyncratic bespoke licenses, such as this one: https://github.com/acl2/acl2/blob/05be8a89ffaa39e320915680810e277a035fbd41/books/interface/infix/sloop.lisp#L15-L21

**Comment by airbornemihir** [comment]
That's an interesting licence. I stand corrected.

**Comment by myall86** [comment]
Added a 3-clause BSD license to the files.

Thanks,
Cuong

**Comment by kini** [comment]
Thanks!  Good catch about your contributions at UT being copyright by the Regents of the University of Texas; I forgot about that.

While you're at it, you could also do the same thing for the existing files in the `serial-adder` directory?

**Comment by myall86** [comment]
I gotta go now. I'll do that later tonight or tomorrow.

Cheers,
Cuong

**Comment by MattKaufmann** [comment]
I'd like to accept this pull request.  Any reason why not?

**Comment by ragerdl** [comment]
I think it's clear to merge.  I'll go ahead and do it and reap the repercussions. :)

**Comment by MattKaufmann** [comment]
Regarding:

> That's an interesting licence. I stand corrected.

But you almost got it right, Mihir: I think that last I checked a few
years ago, GPLv2 and 3-clause BSD were the only licenses approved for
books owned by UT (i.e., copyrighted by UT Regents).

-- Matt

**Pull request merged**
