### PR TITLE
Add and improve lemmas in books/std/lists/{take,repeat}.lisp

### PR DESCRIPTION
**Pull request by airbornemihir**

### CODE REVIEW

**Comment by airbornemihir** [comment]
I don't know if anyone's getting notified for my changes of base branch above, but I did it to test a hunch that extraneous commits would disappear from the "commits" tab of this PR (https://github.com/acl2/acl2/pull/1123/commits) after having been merged into testing by @acl2buildserver . This turns out to be correct.

**Comment by MattKaufmann** [comment]
Sorry, I'm not tracking this.  Is the bottom line that everything in
pull request #1123 is already in master?

Thanks,
Matt

**Comment by airbornemihir** [comment]
Hi Matt,
Since this PR is limited to STD books and filesystem books, I think it's perfectly fine if you decide this is outside your usual turf - someone or the other who works with STD will likely find the time to review my changes soon. 
For the same of completeness, let me answer your question about the bottom line: no, that's not the case; there is indeed new material in this pull request. I was talking above about a quirk of the GitHub user interface where commits by other people (merge commits by Sol and others, in this case) which have not yet made their way to my target branch (testing in this case) show up as commits introduced by me. This clutters up the diff, the list of files changed, and the list of commits. The two lines above saying I "changed the base branch" resulted from my hacky attempt to clear up this visual clutter, which seems to have worked. People making pull requests in the future may or may not want to do this, but now we know it can be done.
Best,
Mihir.

**Comment by MattKaufmann** [comment]
Thanks, Mihir; I don't really understand all that, but you answered my question.  So far I've gotten by with minimal understanding of git, thanks to help from you and others, which has made it possible for me to continue on the project.  (Mostly kidding about the need to be able to proceed with minimal understanding of git -- not completely though.)

**Comment by airbornemihir** [comment]
I have myself refused for years to learn about certain overly complicated features of git and I've gotten along fine, haha.

**Pull request merged**
