### PR TITLE
A new book about coprime integers.

### PR DESCRIPTION
**Pull request by nadezhin**
New book projects/quadratic-reciprocity/coprime.lisp
contains defintion of coprime integers and its corollaries:
     (1) Existence of modulo inverse
     (2) Chinese remainder theorem for two remainders.

### CODE REVIEW

**Comment by nadezhin** [comment]
I just have found a directory `workshops/2000/russinoff-short` where @russinoff did this work 16 years ago. I didn't notice it because it is not in ACL2 documentation. I think that it would be nice to add to documentation a section arithmetic/number-theory and gather there links to various number-theory books. Now I'm looking at @russinoff 's book and request to postpone the review of this pull request.

**Comment by jaredcdavis** [comment]
> I think that it would be nice to add to documentation a section arithmetic/number-theory and gather there links to various number-theory books.

FWIW, it's definitely unfortunate that so many books aren't included in the documentation.  If anyone with time has interest in documenting the details or mere existence of more books, especially important books like the various arithmetic libraries, that would (of course) be great.

**Comment by nadezhin** [comment]
I discussed addition `arithmetic/number-theory` topic to XDOC and got an answer that `number-theory` is not part of `arithmetic`. This is true.
However, `arithmetic` topic in XDOC has already subtopics that are not parts of arithmetic. `arithmetic/cowles` is about algebra -groups and rings. 
I think about renaming XDOC `arithmetic` topic to `math` topic.
Then `math/number-theory` and `math/cowles` topics seem more natural.

**Comment by ragerdl** [comment]
That change makes sense to me, though it may be a non-trivial amount of work to fix up all of the references to what is currently `acl2::arithmetic`.  Also, we'd leave most of `acl2::arithmetic` unchanged -- just put it under `math`.  Thoughts from others like @MattKaufmann , @jaredcdavis ?

**Comment by russinoff** [comment]
Maybe math/cowles is not the best name for that directory.  Maybe
math/algebra?

**Comment by MattKaufmann** [comment]
I like the idea of adding a new MATH topic directly under TOP, moving
the existing ARITHMETIC topic to be a child of MATH, and moving or
renaming some subtopics of ARITHMETIC as appropriate.

Perhaps someone would like to propose to this list an explicit
structure of topics under MATH, so that once nobody has objected for a
couple of days, it will be trivial to implement that structure (by
changing a few parents and write a very short MATH topic).

-- Matt

**Comment by nadezhin** [comment]
I shall try to prepare such a list.
Can this list contain links to topics from workshops directories as well ?

**Comment by MattKaufmann** [comment]
Thanks, Dmitry!  If you care to include links to topics under
books/workshops/, I think that would be great.

I was thinking of something simple.  The simplest version would just
be the following, which means that nothing changes except that a new
top-level topic, MATH, would have the existing topic, ARITHMETIC, as
its only child.

MATH
  ARITHMETIC

But a more sophisticated version could be something like the following
(but I haven't really thought about it -- I'm too lazy to do that, so
this is just to give a rough idea).

MATH
  ALGEBRA [formerly COWLES]
  ARITHMETIC
  BIT-VECTORS
    ARITH-EQUIVS
    BITOPS
    IHS
    RTL

-- Matt

**Comment by ragerdl** [comment]
Note that Matt's reply doesn't show up formatted properly in the email.  Glad it's right here!

**Comment by nadezhin** [comment]
The XDOC changes are submitted in a new pull request #608 . 
This pull request will be cancelled and probably reimplemented.

**Comment by russinoff** [comment]
Thanks, I'll take a look.

**Comment by nadezhin** [comment]
I cancel this pull request.

**Pull request closed without merging**
