### PR TITLE
Add theorem and theory invariant to osets.

### PR DESCRIPTION
**Pull request by acoglio**

### CODE REVIEW

**Review by gjurgensen — APPROVED** [review]
LGTM.

**Comment by gjurgensen** [comment]
I'll mention that the prevailing style in osets seems to be capitalizing variables representing sets, but plenty of theorems are already breaking that convention.

**Comment by acoglio** [comment]
> I'll mention that the prevailing style in osets seems to be capitalizing variables representing sets, but plenty of theorems are already breaking that convention.

Yes, I noticed that, but I was actually thinking of proposing a PR to lowercase all of them at some point 😄

**Comment by ericwhitmansmith** [comment]
LGTM. (I see that you are matching the existing naming scheme, which could be improved later.)

**Review by ericwhitmansmith — APPROVED** [review]

**Pull request merged**
