### PR TITLE
Make no-sqrt.lisp certifiable in all ACL2 versions

### PR DESCRIPTION
**Pull request by kini**
Another old branch I found lying around. I think I was planning to edit `iter-sqrt.lisp` in a similar fashion, to add an actual `sqrt` function and prove `(equal (* (sqrt x) (sqrt x)) x)` for appropriate `x` (in ACL2(r) only, of course). But I never got around to figuring out how to do that, haha...

Link to diff view of this PR with whitespace changes ignored: https://github.com/acl2/acl2/pull/1135/files?w=1

#### Make `no-sqrt.lisp` certifiable in all ACL2 versions

By replacing `realp` with `real/rationalp` and `complexp` with `complex/complex-rationalp`, this book becomes certifiable with standard ACL2.  As far as I've seen, usually this is done to make ACL2-certifiable books become ACL2(r)-certifiable rather than vice versa, but I think it's nice to try to make ACL2(r)-related books ACL2-certifiable if possible, too.

The final theorem says that if x^2 = 2, then x is `real/rationalp` and not `rationalp`.  In ACL2(r) this means that x is an irrational real number, but in standard ACL2, this means that x is both rational and not rational, which is impossible (i.e. such an x cannot exist).  So for the standard ACL2 case (`#-non-standard-analysis`), I make the theorem a corollary which simply states that there is no x such that x^2 = 2.

The comments in this file need to be fixed as well -- they were written in a way that implied that ACL2(r) had become the mainstream ACL2 distribution, whereas in fact it is (currently) maintained in parallel with a standard version of ACL2 that does not include non-standard analysis support.  I'll do that in a separate commit.

#### Clean up comments

See parent commit's message for details.

#### Move iter-sqrt to nsa/sqrt-iter

(I figure it's better for the name to start with "sqrt" so it's visually close to sqrt.lisp in a directory listing.)

#### Deduplicate sqrt-iter.lisp and sqrt.lisp

Since after the previous few commits sqrt-iter.lisp was very similar to the first part of sqrt.lisp, this commit now removes the first part of sqrt.lisp and replaces it with (include-book "sqrt-iter") to avoid having two copies of those events lying around.

### CODE REVIEW

**Comment by MattKaufmann** [comment]
I'm glad you requested @rubengamboa for a review.  In particular, I wonder about this comment:

"BOZO: We should also prove that you can get the actual square root in ACL2(r)."

I suspect that Ruben has proved this somewhere, but I'm not sure.

(By the way, I gave a quick look -- probably not as careful a look as Ruben will give it -- and I think this is a nice improvement.)

**Comment by kini** [comment]
Thanks for pointing out that BOZO comment. I think I had intended that more as a note to myself (I made these commits in 2017 so I don't quite remember...). Since I never ended up doing that, maybe I should remove the note? Though I do think it would be nice to include an ACL2(r) exact sqrt function in the same book as the iterated approximate version that works in both ACL2 and ACL2(r).

I don't know the first thing about ACL2(r), but I was under the impression that you might be able to simply iterate the approximate sqrt function an i-large number of times to produce a number i-close to the exact square root, and then take its standard part to get the exact square root, or something like that. If so, that would be another reason to define the function right here in the same book as the approximation function.

As to whether an actual sqrt function has been defined elsewhere, I'm not sure, but I couldn't find one in this repository at least.

**Comment by MattKaufmann** [comment]
Here are relevant events in books/nonstd/nsa/sqrt.lisp:

    (defun-std acl2-sqrt (x)
      (standard-part (iter-sqrt (fix x) (/ (i-large-integer)))))

    (defthm-std sqrt-sqrt
      (implies (and (realp x)
		    (<= 0 x))
	       (equal (* (acl2-sqrt x) (acl2-sqrt x)) x))
      :hints ....)

**Comment by kini** [comment]
Huh, no idea how I missed that, thanks. Actually, `books/nonstd/nsa/sqrt.lisp` looks very much like a rework of `books/nonstd/sqrt/iter-sqrt.lisp` for ACL2(r). They're almost the same for the entirety of `iter-sqrt.lisp`, and then `sqrt.lisp` has a bunch of extra stuff going on to define the actual sqrt function in a manner similar to what I guessed above (and as you pasted).

Since this PR is about making a single book (`no-sqrt.lisp`) certify in both ACL2 and ACL2(r), I guess the logical extension of that to `iter-sqrt.lisp` and `sqrt.lisp` would be to combine them into a single book that certifies in both ACL2 and ACL2(r). But given the current structure, maybe Ruben wanted to keep them separated?

**Comment by kini** [comment]
I added some more commits to move the `books/nonstd/sqrt/` books into `books/nonstd/nsa` and include-book the `iter-sqrt` book (which I renamed to `sqrt-iter`) into the `sqrt` book in order to de-duplicate the shared or almost-shared code.

Now `books/nonstd/nsa/sqrt-iter.lisp` and `books/nonstd/nsa/sqrt-2.lisp` certify under both standard ACL2 and ACL2(r), while `books/nonstd/nsa/sqrt.lisp` continues to be certifiable only by ACL2(r).

Unfortunately it seems github isn't smart enough to show the changes I've made in a sensible way all at once, but if you look at the individual commits hopefully it shouldn't be too hard to understand what I did.

**Comment by kini** [comment]
@airbornemihir Did you mean to merge this PR? @rubengamboa hasn't gotten a chance to review it yet.

**Comment by MattKaufmann** [comment]
@airbornemihir  @kini  Moreover, the ACL2(r) build is broken, as noticed by @ragerdl , who pointed me here for the error in certifying books/nonstd/workshops/2013/helms-gamboa-quantum/support/quantum.lisp:

http://leeroy2.defthm.com/job/acl2-multiple-flavors-and-lisps-monthly-regression-everything/ACL2_PAR=no_p,ACL2_REAL=r,LISP=ccl/11/console

This is the error message.  Perhaps iter-sqrt was renamed?

       | ACL2 Error in ( DEFUN QUSTATE-NORM-E ...):  The symbol ITER-SQRT (in
       | package "ACL2") has neither a function nor macro definition in ACL2.
       | Please define it.  See :DOC near-misses.  Note:  this error occurred
       | in the context (ITER-SQRT (QUSTATE-AMPLITUDES-SUM-SQUARES X) E).

I don't know if the best way to fix this is just to fix it, or to back it out so that @rubengamboa can review it first (but still, someone should fix it).

**Comment by airbornemihir** [comment]
Hi Matt, Keshav - the only thing I can think of is to revert this 
change. Let me try.

**Comment by rubengamboa** [comment]
Mugir,

Let me look at it first. I’m totally out of context but I’ll take at least
a quick look this morning.


Clear skies,
Ruben

—
Ruben Gamboa
Professor and Head
Department of Computer Science
University of Wyoming

**Comment by airbornemihir** [comment]
Good morning, Ruben. OK, I'll hold off for now.

**Comment by airbornemihir** [comment]
[0001-Roll-back-changes-from-1135.patch.txt](https://github.com/acl2/acl2/files/5007260/0001-Roll-back-changes-from-1135.patch.txt)
Here's a patch that reverses Keshav's changes from this PR, if that's chosen to be the path forward. If one downloads this file under the name 0001-Roll-back-changes-from-1135.patch into the ACL2 sources directory, one should be able to run "git am 0001-Roll-back-changes-from-1135.patch" to apply it.

**Comment by kini** [comment]
I'd like to avoid undoing the changes in this PR, because that will make the history of the changed files look pretty confusing, especially if my changes are eventually reinstated. I'd prefer to just fix whatever breakage has occurred.

The immediate fix for the issue with `iter-sqrt` is to change references to it to references to `sqrt-iter`, since I renamed `iter-sqrt` to `sqrt-iter` and change `include-book` references to point to `nonstd/nsa/sqrt-iter` instead of `nonstd/sqrt/iter-sqrt`. (Sorry, I didn't see that it was referenced from the workshop books.) Not sure what else might be broken.

**Comment by airbornemihir** [comment]
Sure. I'm happy for you, Keshav, to fix this (I have no opinion on the ACL2r details). I'm also happy to apply my patch (i.e. undo your changes) and push myself if someone should ask in the next few minutes. Otherwise, I will leave this alone until tomorrow so everyone has a chance to figure out the right thing to do.

**Comment by rubengamboa** [comment]
Yeah, I think the only thing needed to fix this is to change iter-sqrt to
sqrt-iter in
books/nonstd/workshops/2013/helms-gamboa-quantum/support/quantum.lisp. I’m
trying that now.

What about books/coi/super-ihs/iter-sqrt.lisp? Should that change, too?

Clear skies,
Ruben

—
Ruben Gamboa
Professor and Head
Department of Computer Science
University of Wyoming

On July 31, 2020 at 9:31:01 AM, Mihir Mehta (notifications@github.com)
wrote:

Sure. I'm happy for you, Keshav, to fix this (I have no opinion on the
ACL2r details). I'm also happy to apply my patch (i.e. undo your changes)
and push myself if someone should ask in the next few minutes. Otherwise, I
will leave this alone until tomorrow so everyone has a chance to figure out
the right thing to do.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1135#issuecomment-667182448>, or
unsubscribe

**Comment by MattKaufmann** [comment]
I'll take the comment from @rubengamboa suggesting a successful review.  Thus, I'm willing to deal with this if it's trivial, by doing a nonstd regression and making easy changes, such as renaming iter-sqrt to sqrt-iter in the failing book.  I won't touch books/coi/super-ihs/iter-sqrt.lisp, since it looks to me like there's no need.  If there's anything beyond this I'll probably leave the rest to others, since this has nothing to do with me.

**Comment by MattKaufmann** [comment]
Sorry, my comment had a typo in the poorly worded first sentence.  I meant to say: I'll take the comment from @rubengamboa as suggesting that he is OK with the change.

**Comment by rubengamboa** [comment]
Yeah, that’d be great.  I was trying to make sure it worked after the
minimal changes, but I can’t get my LISP environment to work at all on my
new laptop. There’s some sort of error in CCL and SBCL that’s messing me
up, so you’ll get this totally fixed before I even get the latest ACL2
compiled!  Sigh….

Clear skies,
Ruben

—
Ruben Gamboa
Professor and Head
Department of Computer Science
University of Wyoming

On July 31, 2020 at 10:34:09 AM, MattKaufmann (notifications@github.com)
wrote:

Sorry, my comment had a typo in the poorly worded first sentence. I meant
to say: I'll take the comment from @rubengamboa
<https://github.com/rubengamboa> as suggesting that he is OK with the
change.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/acl2/acl2/pull/1135#issuecomment-667216492>, or
unsubscribe

**Comment by MattKaufmann** [comment]
ACL2(r) regression is still broken.  I've pushed a commit (09d883aba0d7f7561266352df9d159e0aa141180) that fixes two failures, including the one found by @ragerdl.  I'll leave it to others to decide how to proceed.  One option might be for @airbornemihir to fix the failures since he is the one who accepted this old pull request without (by accident) adequate testing.  Or perhaps @kini  would be willing to take a look since he doesn't want to revert as @airbornemihir suggested.  Or maybe @rubengamboa can get ACL2(r) installed on his machine and will take a look.  Anyhow, I hope someone fixes this soon; until then, it might be best for @ragerdl to avoid continuous integration testing of ACL2(r) with target "regression".

**Comment by MattKaufmann** [comment]
P.S. I don't know whether ACL2(r) regression was already broken even before @airbornemihir accepted the pull request from @kini .

**Comment by airbornemihir** [comment]
I'm not sure where this is at right now. But, I'm currently building an ACL2r executable so I can find out where the failures are and revert changes there. Please ask me to stop if you're doing something else to resolve this.

**Comment by MattKaufmann** [comment]
@airbornemihir Just FYI, I don't have the impression that the 4 ACL2(r) certification failures that I didn't fix would be fixed by any sort of "revert", unless you're talking about reverting the entire pull request somehow.  Maybe I'm missing something.  (No need to reply; just trying to help a bit when something occurs to me.)

**Comment by airbornemihir** [comment]
@MattKaufmann Yes, the only solution I can think of is to reverse all of 
Keshav's changes. If I'm able to build the regression successfully after 
that, I'll probably put in a pull request.
If you have a moment, could you please answer my question on Slack?

**Comment by kini** [comment]
I can confirm that the ACL2(r) regression works at `a9ad83f1d70e79e9da98dd09df444f5fca2a8ddf`, which is the first parent of Mihir's merge commit.

By the way, Mihir, please don't use octopus merges (merges with more than two parents) because it means that there's now no easy way to tell, in theory, whether the breakage was caused by my PR or PR #1158, which your merge commit merged into the `testing` branch simultaneously. Of course, I assume that it's caused by my PR since I doubt Mertcan touched anything relevant to what's breaking, but still as a general rule it's not a good idea to merge multiple branches in a single commit, which is why `git` kind of makes you go out of your way to make such a merge.

**Comment by MattKaufmann** [comment]
@kini Thanks; that's useful info.  Also of interest, I suppose, might be whether the ACL2(r) regression passes at the point just before @airbornemihir accepted your pull request.

**Comment by kini** [comment]
Yes -- a9ad83f1d70e79e9da98dd09df444f5fca2a8ddf, the first parent of Mihir's merge commit, is the point just before Mihir accepted my pull request (and Mertcan's simultaneously).

**Comment by MattKaufmann** [comment]
@kini Oh, thanks; I misunderstood your earlier post (as having referred to the point at which you made the pull request).  Sigh, once again I've gotten confused about git.  Anyhow, that's good news, I think.

**Comment by ragerdl** [comment]
It may make sense to disable the offending books in acl2(r) with a cert-param -- so long as they have non-trivial problems to fix.  E.g., the one at http://leeroy2.defthm.com/job/acl2-multiple-flavors-and-lisps-monthly-regression-everything/ACL2_PAR=no_p,ACL2_REAL=r,LISP=ccl/16/console shows an issue with a rewrite loop.

**Comment by ragerdl** [comment]
Mihir says he think he has fixes that pass.  FYI

**Comment by ragerdl** [comment]
Please abstain from patching this.  I've got something that thus far is working.  For more info see #1159.

**Pull request merged**
