### PR TITLE
Small documentation update

### PR DESCRIPTION
**Pull request by airbornemihir**

### CODE REVIEW

**Comment by kini** [comment]
I think you accidentally got some rebased versions of three of Alessandro's commits (or pre-rebase versions?) on your branch.

**Comment by airbornemihir** [comment]
@kini It's stale caching on GitHub's part. I've dealt with this kind of 
thing before and as far as I understand, there nothing that can be done 
about the misleading diff and the misleading list of commits - GitHub 
just won't update it.

**Comment by kini** [comment]
Hmm. Well, your change looks fine to me, but I'm not sure what will happen if I click "Merge pull request" on github when it's in this screwed-up state. I'll try to merge your changes into testing manually using the `git` command line client.

**Comment by airbornemihir** [comment]
I just realised that perhaps there's value in GitHub not changing diffs partway through the life of a pull request. It would make a mess of review comments referring to specific lines of code. This also seems to be the reason for the warning GitHub displays when one changes the base branch of a pull request.

**Pull request merged**
